### ISSUE TITLE
Build dockerfiles not updating properly?

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2253]
As far as I can see the changes in https://github.com/adoptium/infrastructure/pull/2240 have not yet taken effect in the dockerfiles for some reason. 

Looking at a recent github test, it looks like https://github.com/adoptium/infrastructure/pull/2223/checks?check_run_id=2849714322 (as an example has the following in it:
```
 Proceed (y/n)? ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/uninstall.py", line 86, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 672, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 380, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 423, in _allowed_to_proceed
    return ask('Proceed (y/n)? ', ('y', 'n')) == 'y'
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 203, in ask
    response = input(message)
EOFError: EOF when reading a line
Loaded plugins: fastestmirror, ovl
Cleaning repos: base centos-sclo-rh centos-sclo-sclo epel extras
              : testing-devtools-2-centos-6 updates
```
which suggests that it may not have run through to competion, or failed some way. It certainly doesn't appear to have run any of the `adoptopenjdk_install` invocations. But it seems to be still showing as a green 'pass" which doesn't seem right (if this is expected, we need to document it. If it's not right it needs to properly fail the check in this sutation)

**Comment by sxa** [comment]
Appears ok - Linux/x64 and Linux/aarch64 are using the boot JDK from the correct location. No idea what was fixed to do this but doesn't seem to have been tracked through this issue
