### ISSUE TITLE
Remote call on test-macstadium-macos1014-x64-1 ,-2 ,-3 failed 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2281]
This issue caused a catastrophic fail of testing on mac over the weekend.  Please consider it urgent given the upcoming release.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name? 
ALL test suites affected (can not fetch test material in order to setup and run tests).

- Is there an existing issue elsewhere covering this?  Do not find an existing issue
- Which machine(s) does it work on?
test-macstadium-macos1012-x64-1

- Which machine(s) does it fail on?
test-macstadium-macos1014-x64-1
test-macstadium-macos1014-x64-2
test-macstadium-macos1014-x64-3

- Do you have a link to a Grinder re-run if the test with the failure?

All tests from the weekend runs were sent to either test-macstadium-macos1014-x64-1, 
test-macstadium-macos1014-x64-2 or test-macstadium-macos1014-x64-3 and failed in the same way.  The one passing test was sent to test-macstadium-macos1012-x64-1.

<img width="382" alt="Screen Shot 2021-07-18 at 10 16 43 AM" src="https://user-images.githubusercontent.com/2836948/126070708-56d5fa2e-a113-4b2b-a62b-1c37fe914250.png">

Links to any of the weekend runs show this same failure:
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_x86-64_mac/173
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_mac/44/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/506/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_x86-64_mac/221/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.perf_x86-64_mac/30/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_x86-64_mac/504/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.system_x86-64_mac/498/

Grinder link with a small test target to hit same issue (LABEL=test-macstadium-macos1014-x64-1):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1114/console

Any other details:

Console output:
```
The recommended git tool is: git
[Pipeline] echo
Exception: java.io.IOException: Remote call on test-macstadium-macos1014-x64-1 failed

```

**Comment by smlambert** [comment]
As no tests can successfully setup on these machines, I have marked these 3 machines offline with a link to this issue.

**Comment by Haroon-Khel** [comment]
On `test-macstadium-macos1014-x64-1`, the tests themselves seem to work fine. So we can rule that out

```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DISABLED test targets:
	SyntheticGCWorkload_TestCase_0
	cmdLineTester_libpathTestRtfChild_0

PASSED test targets:
	testXXArgumentTesting_0

TOTAL: 3   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 2   SKIPPED: 0
ALL TESTS PASSED
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

**Comment by Haroon-Khel** [comment]
Ref https://github.com/adoptium/infrastructure/issues/1910

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1088/console was the last job, sanity openjdk test, that I ran on test-macstadium-macos1014-x64-2 **after** having run the playbook on the machine. So I don't think these failures are to do with having had the playbook run on them

**Comment by Haroon-Khel** [comment]
Just noticed this on the jenkins log of `test-macstadium-macos1014-x64-1` 

```
Jul 19, 2021 5:21:30 P.M. jenkins.model.Jenkins <clinit>
SEVERE: Failed to load Jenkins.class
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5385)
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Haroon-Khel** [comment]
On -2

```
Jul 15, 2021 7:54:15 P.M. jenkins.model.Jenkins <clinit>
SEVERE: Failed to load Jenkins.class
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5385)
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Jul 15, 2021 7:54:15 P.M. hudson.remoting.UserRequest perform
WARNING: LinkageError while performing UserRequest:hudson.Launcher$RemoteLauncher$KillTask@3a7a114e
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5385)
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

And on -3

```
Agent successfully connected and online
Jul 15, 2021 7:53:51 P.M. jenkins.model.Jenkins <clinit>
SEVERE: Failed to load Jenkins.class
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5385)
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Jul 15, 2021 7:53:51 P.M. hudson.remoting.UserRequest perform
WARNING: LinkageError while performing UserRequest:hudson.Launcher$RemoteLauncher$KillTask@359d96a0
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5385)
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

I've brought -1 back online, but changed its `mac` label to `macXXX` so it should not be picked up for any build/test/installer job

**Comment by sxa** [comment]
(The following was tested on `-2`)

@Haroon-Khel The default `java` on the machine is AdoptOpenJDK JDK-16:
```
test-macstadium-macos1014-x64-2:~ jenkins$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
test-macstadium-macos1014-x64-2:~ jenkins$ 
```
If I start the jenkins agent using JDK8 (Launch Method -> Advanced -> JavaPath = `/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java`) then the problem goes away. This is likely a side effect of the JDK16 installed by the recently playbook runs. The problem would not have been visible until the next time the agent was restarted since it will continue to use the existing JVM until that time.
If there is a clean way to set JDK8 as the default that would likely solve the problem, otherwise (even if only as a temporary solution) we could make the `JavaPath` change as I have done on `-2`

**Comment by Haroon-Khel** [comment]
@sxa Good find 👍🏻 I'll test this on the other 2. It would be interesting to know why jdk 16 does this to the 10.14 machines

**Comment by Haroon-Khel** [comment]
After running a few more grinders on -3, the other boot jdks, 10 to 15 (not 12), installed on that machine do not give this error. I think the reason the bootjdks become the default java on the macos machines is because during the playbook they are installed onto the machine using an installer

https://github.com/adoptium/infrastructure/blob/9f60b0e9d5bb879f92c6b9926e925d769610ef95/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml#L151

rather than being unzipped and linked as we do for our linux distros. We do offer macos binaries in tar.gz format aswell as .pkg so the change to doing it the linux way is feasible

**Comment by Haroon-Khel** [comment]
With the change from hotspot to temurin, on newly setup machines bootjdks on macos are found in `/Library/Java/JavaVirtualMachines/temurin-*.jdk/` rather than `/Library/Java/JavaVirtualMachines/adoptopenjdk-*.jdk/`. The build scripts still look in the former directory, https://github.com/adoptium/temurin-build/blob/c4842313fe56dacd4986e35d34d132db979bf8df/build-farm/platform-specific-configurations/mac.sh#L82 as do the playbooks https://github.com/adoptium/infrastructure/blob/87c0db93880c4b0c16449dfab3f46e9e3f853730/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml#L28 when looking for a bootjdk

**Comment by smlambert** [comment]
Marking https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-3/ offline, test jobs sent to it during March jdk18 with:
`Exception: java.io.IOException: Remote call on test-macstadium-macos1014-x64-3 failed`

Job failures (looks like any test job sent to it will fail in the same way): 
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.perf_x86-64_mac/26 
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_0/26

**Comment by Haroon-Khel** [comment]
For https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-3/, I have changed the java path in its jenkins config to java 8

Running a sanity test on the machine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4469/console. If it passes, we can close this issue as this was the last machine affected by this issue

**Comment by sxa** [comment]
Looks good. If we've got problems that we believe are related to running the agent on a later version of the JVM can we create a separate issue for that, since I have definitely been running the agent with 11+ on other platforms so it would be good to understand and try and fix in the future, and the issue is a good way of recording the problem.
