### ISSUE TITLE
Ansible request for <libXrender.a > on test-ibm-aix71-ppc64-*

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2292]
- [libXrender.a ] Missing install on test-ibm-aix71-ppc64-*

Details:
java/beans/* along with some other tests failed with 

```
java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib/libawt_xawt.so: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib/libawt_xawt.so, LIBPATH=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib/jli:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/../lib, LD_LIBRARY_PATH= : 	0509-022 Cannot load module /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/lib/libawt_xawt.so.
	0509-150   Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
	0509-152   Member shr_64.o is not found in
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
```
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_1/9/

This happened to   test-ibm-aix71-ppc64-* , no issue with test-osuosl-aix71-ppc64-*. 
reran on test-osuosl-aix72-ppc64-2 no this issue:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/236/

All jdk8, jdk11 and jdk16 are affected.

Related with https://github.com/adoptium/adoptium/issues/62, https://github.com/adoptium/adoptium/issues/63

**Comment by sxa** [comment]
Dup of https://github.com/adoptium/infrastructure/issues/2069
