### ISSUE TITLE
Centos 6 docker build check has been failing for recent pull requests

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2301]
The most recent failure https://github.com/adoptium/infrastructure/pull/2300/checks?check_run_id=3442260626

It seems the process has trouble installing ansible

```
Successfully installed pip-21.2.4
Collecting ansible
  Downloading ansible-4.4.0.tar.gz (35.4 MB)
Collecting ansible-core<2.12,>=2.11.3
  Downloading ansible-core-2.11.4.tar.gz (6.8 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
...
pip3 install ansible' returned a non-zero code: 2
Error: exit status 2

```

**Comment by Haroon-Khel** [comment]
I've changed the method of installation to a simple yum command and it seems to have fixed it

**Comment by Haroon-Khel** [comment]
Closing as https://github.com/adoptium/infrastructure/pull/2303 is merged
