### ISSUE TITLE
JDK8 jdk_nio_2 passes only on build-equinix-ubuntu1604-armv7l-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2374]
jdk_nio_2 from the jdk8 hs extended openjdk test suite seems to pass only on build-equinix-ubuntu1604-armv7l-1. 

Latest pass: https://ci.adoptopenjdk.net/job/Grinder/2309/console

Last failure https://trss.adoptium.net/output/test?id=6180ca5ec6182d0217d9cf62, on test-docker-ubuntu2004-armv7l-2

The failing tests are 

```
java/nio/channels/FileChannel/ClosedByInterrupt.java.ClosedByInterrupt
java/nio/channels/FileChannel/InterruptDeadlock.java.InterruptDeadlock
```

Both fail with the same error

```
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.ArrayIndexOutOfBoundsException: -1 (not expected)
java.lang.RuntimeException: Test failed
	at ClosedByInterrupt.main(ClosedByInterrupt.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test
```

**Comment by Haroon-Khel** [comment]
11:57:12  class java.nio.channels.AsynchronousCloseException (expected)
11:57:12  STDERR:
11:57:12  Reader thread failed with: java.lang.ArrayIndexOutOfBoundsException: -1
11:57:12  Reader thread failed with: java.lang.ArrayIndexOutOfBoundsException: -1
11:57:12  java.lang.RuntimeException: Test failed - see log for details
11:57:12  	at InterruptDeadlock.main(InterruptDeadlock.java:133)
11:57:12  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:57:12  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:57:12  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:57:12  	at java.lang.reflect.Method.invoke(Method.java:498)
11:57:12  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
11:57:12  	at java.lang.Thread.run(Thread.java:750)
11:57:12  
11:57:12  JavaTest Message: Test threw exception: java.lang.RuntimeException
11:57:12  JavaTest Message: shutting down test

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2600/console
jdk 17 on test-docker-ubuntu2004-armv7l-2 again

```
12:08:54  STDOUT:
12:08:54  Transferred 2147484671 bytes
12:08:54  STDERR:
12:08:54  java.lang.RuntimeException: Too few bytes transferred: 2147483647 < 2147484671
12:08:54  	at Transfer2GPlus.testToWritableByteChannel(Transfer2GPlus.java:125)
12:08:54  	at Transfer2GPlus.main(Transfer2GPlus.java:61)
12:08:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:08:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
12:08:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:08:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
12:08:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
12:08:54  	at java.base/java.lang.Thread.run(Thread.java:833)
12:08:54  
12:08:54  JavaTest Message: Test threw exception: java.lang.RuntimeException
12:08:54  JavaTest Message: shutting down test
12:08:54  
12:08:54  
12:08:54  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Too few bytes transferred: 2147483647 < 2147484671
12:08:54  --------------------------------------------------
12:16:34  Test results: passed: 438; failed: 1
12:16:48  Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
12:16:48  Results written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16376692082326/jdk_nio_2/work
12:16:48  Error: Some tests failed or other problems occurred.
12:16:48  
12:16:48  jdk_nio_2_FAILED
```

Fails on build-equinix-ubuntu1604-armv7l-1 too for jdk17
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2602/console

**Comment by Haroon-Khel** [comment]
Found this upstream issue https://bugs.openjdk.java.net/browse/JDK-8054039

**Comment by Haroon-Khel** [comment]
The jdk 11 failure java/nio/file/DirectoryStream/SecureDS.java.SecureDS
jdk 17 failure java/nio/channels/FileChannel/Transfer2GPlus.java.Transfer2GPlus

**Comment by Haroon-Khel** [comment]
Upstream issue for the jdk17 test failure (java/nio/channels/FileChannel/Transfer2GPlus.java.Transfer2GPlus) https://bugs.openjdk.java.net/browse/JDK-8272095

Fails on linux aarch64, which is the actual architecture of these arm32 docker containers

**Comment by sxa** [comment]
To summarise the above as we have three separate problems here and it's not quite clear where each is happenin.
- JDK8: `InterruptDeadlock` failure (listed as intermittent - is it for us? -  and [fixed upstream](https://bugs.openjdk.java.net/browse/JDK-8054039) for some codebase). Is this only failing on the test-equinix container?
- JDK11: `SecureDS` failure `SecureDirectoryStream not supported` - no know upstream issues.
- JDK17: `Transfer2GPlus` failure - known and seen on Linux/aarch64 - probable kernel issue. Can we run this test on [test-sxa-armv7-raspbian-pi4](https://ci.adoptopenjdk.net/computer/test-sxa-armv7-raspbian-pi4/) - I can then switch that machine to use a 64-bit kernel (no other differences, and without docker) and we can see if it starts happening there too.

**Comment by Haroon-Khel** [comment]
>JDK17: Transfer2GPlus failure - known and seen on Linux/aarch64 - probable kernel issue. Can we run this test on test-sxa-armv7-raspbian-pi4 - I can then switch that machine to use a 64-bit kernel (no other differences, and without docker) and we can see if it starts happening there too.

Running on https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2604/console

**Comment by Haroon-Khel** [comment]
>Running on https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2604/console

Failed due to missing `ant`
Rerunning https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2605/console

**Comment by sxa** [comment]
`Transfer2GPlus` fails for me on my Pi4 with a 32-bit kernel: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2606/console

**Comment by sxa** [comment]
`Transfer2GPlus` [seems to also fail on a 64-bit kernel](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2608/testReport/) on the same Pi4 (32-bit userland) and on [another 32-bit only system](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2607/testReport/) which also failed due to hitting a 2400s timeout on `jdk/nio/zipfs/ZipFSOutputStreamTest.java.ZipFSOutputStreamTest `

**Comment by Haroon-Khel** [comment]
>JDK11: SecureDS failure SecureDirectoryStream not supported - no know upstream issues.
This failure certainly is not intermittent or machine specific.
    * test-docker-ubuntu2004-armv7l-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2649/console
    * test-docker-ubuntu2004-armv7l-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2650/console
    * test-docker-ubuntu2004-armv7l-3 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2651/console
    * build-equinix-ubuntu1604-armv7l-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2652/console
    * test-sxa-armv7l-ubuntu2004-odroid-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2653/console
    * test-sxa-armv7l-ubuntu2004-odroid-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2654/console
    *test-sxa-armv7-raspbian-pi4 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2655/console

All run the test java/nio/file/DirectoryStream/SecureDS.java.SecureDS for 10 iterations. All failed with the same error

```
java.lang.AssertionError: SecureDirectoryStream not supported.
	at SecureDS.main(SecureDS.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sxa** [comment]
Needs retesting since this was from three years ago

**Comment by sxa** [comment]
Potentially duplicate (network related) of https://github.com/adoptium/infrastructure/issues/2376

**Comment by sxa** [comment]
Another one potentially related to https://github.com/adoptium/infrastructure/issues/3043 @Haroon-Khel - would be good to confirm if these are now covered (especially since the machine int he subject line was decommissioned some time ago)
