### ISSUE TITLE
Jenkins installer job access test-sxa-armv7l-ubuntu2004-odroid-1 get error

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2413]
Jenkins installer job access test-sxa-armv7l-ubuntu2004-odroid-1 by label `docker&&linux&&armv7l` get error:

```
> git rev-parse origindistrT^{commit} # timeout=10
 ​> git config cor.sparsecheckout # timeout=10
 ​> git checkout -f 3257299cd721983e19d13d4eb36a80831a9cb591 # timeout=10
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 180.102.226.206/180.102.226.206:61267
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1157)
		at hudson.FilePath.act(FilePath.java:1146)
		at hudson.FilePath.mkdirs(FilePath.java:1331)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:834)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1289)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/64/consoleFull

arm32 installer for debian was enabled in https://github.com/adoptium/installer/pull/396/files

**Comment by sxa** [comment]
The jenkins agent appears to have stopped on that machine. It only has 2Gb of RAM though and I think some of the tests may need more. Bear in mind that since they are 32-bit bit, the arm32/armv7l systems will be limited in terms of the heap size they are able to use.

I'll try and get the machine back up and running with some additional swap space to see if that helps.

**Comment by smlambert** [comment]
Will also note that the machine has these problems when running sanity.openjdk:

```
Running on test-sxa-armv7l-ubuntu2004-odroid-1 in /ssd/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: java.nio.file.FileSystemException: /ssd/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux: Input/output error
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: FAILURE
```
(from https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/299/console)

**Comment by sxa** [comment]
That was a week ago - I've no idea what was happening at that time ;-), although it did suffer a disk outage at one point

**Comment by sxa** [comment]
I've re-run job 64 and it seemed to run ok on the same systems, therefore I'm going to close this. Please re-open if it is seen again (although subject to my earlier comment about resource limitations - if there are additional machine requirements on these operations we'll need to deal with it as a new requirement)
