### ISSUE TITLE
java/net/Socket/GetLocalAddress.java.GetLocalAddress fails passes only on build machines for aix jdk8 hotspot

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2456]
ref https://github.com/adoptium/aqa-tests/issues/3251

The test java/net/Socket/GetLocalAddress.java.GetLocalAddress from jdk_net_1 in the extended openjdk test suite fails on aix for jdk8 hotspot

```
[2022-01-19T14:56:14.750Z] java.net.NoRouteToHostException: Can't assign requested address (Address not available)
[2022-01-19T14:56:14.750Z] 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[2022-01-19T14:56:14.750Z] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```
Trss link
https://trss.adoptium.net/output/test?id=61e84e1fa7df1a2924029952

Deep history shows it fails on test machines

Passes on build-osuosl-1 https://ci.adoptopenjdk.net/job/Grinder/3275/console

**Comment by Haroon-Khel** [comment]
Passes on 

build-osuosl-aix71-ppc64-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3575/console
test-osuosl-aix715-ppc64-4 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3578/console

Fails on 
test-osuosl-aix71-ppc64-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3571/console
test-osuosl-aix71-ppc64-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3572/console
test-osuosl-aix72-ppc64-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3573/console
test-osuosl-aix72-ppc64-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3574/console
build-osuosl-aix71-ppc64-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3576/console
test-osuosl-aix715-ppc64-3 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3577/console

**Comment by Haroon-Khel** [comment]
I've noticed that the test runs twice, with ipv4 and ipv6. On the failing machines, the ipv4 test passes while the ipv6 test fails. On a passing machine, build-osuosl-aix71-ppc64-1 for example, in its ipv6 test case I noticed that the test still used the machine's ipv4 address

```
command: main -Djava.net.preferIPv6Addresses=true GetLocalAddress
reason: User specified action: run main/othervm -Djava.net.preferIPv6Addresses=true GetLocalAddress 
Mode: othervm [/othervm specified]
elapsed time (seconds): 0.15
----------configuration:(0/0)----------
----------System.out:(1/64)----------
=================addr: p8-aix1-adopt01/140.211.9.10 port: 38512
```

While on a failing machine, test-osuosl-aix71-ppc64-1, the test correctly uses the machine's ipv6 address during the ipv6 test case
```
command: main -Djava.net.preferIPv6Addresses=true GetLocalAddress
reason: User specified action: run main/othervm -Djava.net.preferIPv6Addresses=true GetLocalAddress 
...
--- Timeout information end.
elapsed time (seconds): 120.54
----------configuration:(0/0)----------
----------System.out:(2/109)----------
=================addr: p9-aix1-adopt05/2605:bc80:3010:104:0:0:8cd3:963 port: 48888
```
This suggests that the test is running incorrectly on the passing machines.

**Comment by aixtools** [comment]
After research:
- @Haroon-Khel observation re: ipv6: correctly uses the machines IPv6 address - **but add** that it retrieves via DNS.
- One system that passed (the grinder job 3578 did not actually do anything, for some reason) - so ignoring that result (re-running atm and expect it to fail)
- The system mentioned - that seems to be using IPv4 even though IPv6 is specified is because the system is configured to only look for IPv4 addresses (in /etc/netsvc.conf)
- With the following test code (print statements added)
```
import java.net.*;

public class GetLocalAddress implements Runnable {
    static ServerSocket ss;
    static InetAddress addr;
    static int port;

    public static void main(String args[]) throws Exception {
        testBindNull();

        boolean      error = true;
        int          linger = 65546;
        int          value = 0;
        addr = InetAddress.getLocalHost();
        ss = new ServerSocket(0);
        port = ss.getLocalPort();

        System.out.println("addr:" + addr + " port:" + port);
        Thread t = new Thread(new GetLocalAddress());
        t.start();
        Socket soc = ss.accept();

        System.out.println("addr:" + addr + " soc.getLocalAddress:" + soc.getLocalAddress());
        if(addr.equals(soc.getLocalAddress())) {
           error = false;
           }
        if (error)
            throw new RuntimeException("Socket.GetLocalAddress failed.");
        soc.close();
    }

    public void run() {
        System.out.println("run(): addr:" + addr + " port:" + port);
        try {
            Socket s = new Socket(addr, port);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void testBindNull() throws Exception {
        System.out.println("testBindNull()");
        try (Socket soc = new Socket()) {
            soc.bind(null);
            System.out.println("soc.isBound:" + soc.isBound());
            if (!soc.isBound())
                throw new RuntimeException(
                    "should be bound after bind(null)");
            System.out.println("soc.getLocalPort:" + soc.getLocalPort());
            if (soc.getLocalPort() <= 0)
                throw new RuntimeException(
                   "bind(null) failed, local port: " + soc.getLocalPort());
            if (soc.getLocalAddress() == null)
                 throw new RuntimeException(
                   "bind(null) failed, local address is null");
        }
    }

}


testBindNull()
soc.isBound:true
soc.getLocalPort:41115
addr:p9-aix1-adopt05/2605:bc80:3010:104:0:0:8cd3:963 port:41116
run(): addr:p9-aix1-adopt05/2605:bc80:3010:104:0:0:8cd3:963 port:41116
java.net.NoRouteToHostException: Can't assign requested address (Address not available)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at java.net.Socket.<init>(Socket.java:452)
        at java.net.Socket.<init>(Socket.java:262)
        at GetLocalAddress.run(GetLocalAddress.java:68)
        at java.lang.Thread.run(Thread.java:750)
```
- checking nslookup of the address returned by the test:
```
nslookup 2605:bc80:3010:104:0:0:8cd3:963
...
3.6.9.0.3.d.c.8.0.0.0.0.0.0.0.0.4.0.1.0.0.1.0.3.0.8.c.b.5.0.6.2.ip6.arpa        name = p9-aix1-adopt05.osuosl.org.
```
Changing /etc/netsvc.conf from, to:
```
netsvc.conf:
...
# aliases = nis, files
#
hosts=local,bind

Changed to:
...
# aliases = nis, files
#
hosts=local,bind4
```
- test results are:
```
testBindNull()
soc.isBound:true
soc.getLocalPort:41127
addr:p9-aix1-adopt05/140.211.9.99 port:41128
run(): addr:p9-aix1-adopt05/140.211.9.99 port:41128
addr:p9-aix1-adopt05/140.211.9.99 soc.getLocalAddress:/140.211.9.99
STATUS:Passed.
```

Solution: I'll add the IPv6 addresses and verify netsvc.conf ALSO looks at IPv6.

**Comment by aixtools** [comment]
The additional node that 'passed' is because it could not actually run the tests:
```
 + nohup /usr/bin/X11/X -force -vfb -x abx -x dbe -x GLX -secIP 000 :0
 
 Fatal server error:
 Cannot establish any listening sockets - Make sure an X server isn't already running
```

**Comment by aixtools** [comment]
@Haroon-Khel - just ran https://ci.adoptopenjdk.net/job/Grinder/3666/ and https://ci.adoptopenjdk.net/job/Grinder/3665/
- I leave it to you to close this.

**Comment by sxa** [comment]
@Haroon-Khel How is this looking now?

**Comment by Haroon-Khel** [comment]
Grinders (3677 - 3683) pass on all the test machines. Closing. Thanks @aixtools 👍🏻
