### ISSUE TITLE
Possible build failures in jenkins on build-osuosl-aix71-ppc64-1

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2473]
- Please put the system name in the title of this issue. https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1

- Link to any log file showing the problem: Lots of red on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/

- Please describe the issue:
Errors like this ([temurin#4](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/4/console))
```
[](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/4/console#)10:43:33  Execution error: hudson.remoting.RequestAbortedException: hudson.remoting.Channel$OrderlyShutdown: Command Close created at
[Pipeline] echo
10:43:33  hudson.remoting.RequestAbortedException: hudson.remoting.Channel$OrderlyShutdown: Command Close created at
10:43:33  	at hudson.remoting.Request.abort(Request.java:344)
10:43:33  	at hudson.remoting.Channel.terminate(Channel.java:1085)
```

It also seems to spend over ten minutes on this step which [doesn't happen](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/3/consoleFull) when the -2 machine is selected. [Job 5](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/5/console) also shows the same delay at this point
```
[](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/4/console#)10:10:57  [NODE SHIFT] MOVING INTO JENKINS NODE MATCHING LABELNAME xlc13&&aix710&&build&&aix&&ppc64...
[Pipeline] node
10:22:09  Running on [build-osuosl-aix71-ppc64-1](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/) in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin
```

**Comment by sxa** [comment]
This is NOT restricted to a single machine - build machine `-2` is also acting slowly although it took 8 hours to fail at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/3/ - some highlights from the log:

```
[2022-02-16T10:10:46.306Z] checking aix
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] timeout
[2022-02-16T10:10:46.549Z] Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] echo
[2022-02-16T10:10:46.567Z] Cleaning workspace non-hidden files: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/*
[Pipeline] sh
[2022-02-16T10:11:20.864Z] + rm -rf /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/*
[2022-02-16T10:11:22.822Z] Cannot contact build-osuosl-aix71-ppc64-2: java.lang.InterruptedException
[Pipeline] echo
[2022-02-16T10:11:31.845Z] Cleaning workspace hidden files using cleanWs: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin
[Pipeline] cleanWs
[2022-02-16T10:11:32.200Z] [WS-CLEANUP] Deleting project workspace...
[2022-02-16T10:11:32.200Z] [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[2022-02-16T10:12:40.038Z] [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] timeout
[2022-02-16T10:12:40.072Z] Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] echo
[2022-02-16T10:12:40.086Z] [CHECKOUT] Checking out Adopt Pipelines https://github.com/adoptium/ci-jenkins-pipelines.git : master
[Pipeline] checkout
[2022-02-16T10:12:41.330Z] The recommended git tool is: git
[2022-02-16T10:12:41.999Z] No credentials specified
[2022-02-16T10:12:42.171Z] Cloning the remote Git repository
[2022-02-16T10:12:40.311Z] Cloning repository https://github.com/adoptium/ci-jenkins-pipelines.git
[2022-02-16T10:12:41.790Z]  > git init /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin # timeout=10
[2022-02-16T10:12:42.322Z] Fetching upstream changes from https://github.com/adoptium/ci-jenkins-pipelines.git
[2022-02-16T10:12:42.322Z]  > git --version # timeout=10
[2022-02-16T10:12:42.336Z]  > git --version # 'git version 2.20.4'
[2022-02-16T10:12:42.337Z]  > git fetch --tags --force --progress -- https://github.com/adoptium/ci-jenkins-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2022-02-16T10:12:47.073Z] Avoid second fetch
[2022-02-16T10:12:44.823Z]  > git config remote.origin.url https://github.com/adoptium/ci-jenkins-pipelines.git # timeout=10
[2022-02-16T10:12:44.846Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2022-02-16T10:12:47.259Z] Checking out Revision c3a21d1d793f1aabf2c6c52c8178cefa1e3a850e (origin/master)
[2022-02-16T10:12:45.028Z]  > git rev-parse origin/master^{commit} # timeout=10
[2022-02-16T10:12:50.292Z]  > git config core.sparsecheckout # timeout=10
[2022-02-16T10:12:50.311Z]  > git checkout -f c3a21d1d793f1aabf2c6c52c8178cefa1e3a850e # timeout=10
[2022-02-16T10:15:57.734Z] Exception logging commit message for Build #3 of Revision c3a21d1d793f1aabf2c6c52c8178cefa1e3a850e (origin/master): java.io.IOException: Cannot read file /home/jenkins/.config/jgit/co
[Pipeline] sh
[2022-02-16T10:16:20.977Z] + git clean -fdx
```
That's over 5½ hours to get the code from ci-jenkins-pipelines checked out, and then it eventually aborted with an EOF:
```
[2022-02-16T18:16:45.620Z] "./src/hotspot/share/utilities/utf8.hpp", line 87.17: 1540-0198 (W) The omitted keyword "prCould not connect to build-osuosl-aix71-ppc64-2 to send interrupt signal to process
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] timeout
[2022-02-16T18:16:45.705Z] Timeout set to expire in 3 hr 0 min
[Pipeline] {
[Pipeline] archiveArtifacts
[2022-02-16T18:16:54.500Z] Archiving artifacts
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
[2022-02-16T18:22:24.095Z] Execution error: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
[Pipeline] echo
[2022-02-16T18:22:24.097Z] hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
```
Checkout of the openjdk source seemed to take just a few minutes but included an InterruptedException in the log:
```
[2022-02-16T10:17:16.346Z] Could not find a valid openjdk git repository at /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/workspace/build/src so re-cloning the source to openjdk
[2022-02-16T10:17:16.346Z] git clone --depth=1 https://github.com/adoptium/jdk11u.git /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/workspace/./build//src
[2022-02-16T10:17:16.346Z] Cloning into '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/workspace/./build//src'...
[2022-02-16T10:18:13.980Z] Cannot contact build-osuosl-aix71-ppc64-2: java.lang.InterruptedException
[2022-02-16T10:19:38.575Z] Checking out files:   2% (1412/67890)   MChecking out files:   3% (2037/67890)   MChecking out files:   4% (2716/67890)   MChecking out files:   5% (3395/67890)   MChecking out files:
[2022-02-16T10:19:38.575Z] checkoutRequiredCodeToBuild:
[2022-02-16T10:19:38.575Z]   workspace = /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/workspace/./build//src
[2022-02-16T10:19:38.575Z]   BUILD_VARIANT = temurin
[2022-02-16T10:19:38.575Z]   TAG = 
[2022-02-16T10:19:38.575Z]   BRANCH = dev
[2022-02-16T10:21:09.883Z] From https://github.com/adoptium/jdk11u
```

**Comment by sxa** [comment]
I've adjusted the build machines to have `-Dhudson.remoting.Launcher.pingIntervalSec=-1` in the agent JVM launcher options, which appears to be helping the builds get through ok. If we determine the underlying issue here we can remove that again, but it seems to be working as a temporary workaround.

**Comment by sxa** [comment]
FYI @aixtools

**Comment by aixtools** [comment]
The first delay seems to be here:
```
[2022-02-16T10:12:50.311Z]  > git checkout -f c3a21d1d793f1aabf2c6c52c8178cefa1e3a850e # timeout=10
[2022-02-16T10:15:57.734Z] Exception logging commit message for Build #3 of Revision c3a21d1d793f1aabf2c6c52c8178cefa1e3a850e (origin/master): java.io.IOException: Cannot read file /home/jenkins/.config/jgit/co
[Pipeline] sh
[2022-02-16T10:16:20.977Z] + git clean -fdx
```
Not clear to me what this _next_ phase is: only that it is another two hours later:
```
[2022-02-16T18:16:45.620Z] "./src/hotspot/share/utilities/utf8.hpp", line 87.17: 1540-0198 (W) The omitted keyword "prCould not connect to build-osuosl-aix71-ppc64-2 to send interrupt signal to process
[Pipeline] }
...
[Pipeline] // withEnv
[Pipeline] timeout
[2022-02-16T18:16:45.705Z] Timeout set to expire in 3 hr 0 min
[Pipeline] {
[Pipeline] archiveArtifacts
[2022-02-16T18:16:54.500Z] Archiving artifacts
...
[Pipeline] echo
[2022-02-16T18:22:24.095Z] Execution error: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
[Pipeline] echo
[2022-02-16T18:22:24.097Z] hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
```
I'll examine the errpt reports to see if there are any unusual things reported.

**Comment by aixtools** [comment]
- There is nothing in the errpt (literally empty).
- Wait and see if it happens again - anywhere. And if it does, try and ping me if it is still _in action_.

**Comment by sxa** [comment]
I'm having problems resdtarting the jenkins agent on the `-1` build machine at the moment after removing the `-D` parameter that I'd added last week. It seemed to take about 5 minutes to copy the jenkins jar over which suggests there is still an issue:

```

[02/21/22 12:04:20] [SSH] Checking java version of java
[02/21/22 12:04:21] [SSH] java -version returned 1.8.0_261.
[02/21/22 12:04:21] [SSH] Starting sftp client.

[02/21/22 12:04:22] [SSH] Copying latest remoting.jar...

Source agent hash is D866F0B482DB94F38E49B26B465D5DB5. Installed agent hash is D866F0B482DB94F38E49B26B465D5DB5
Verified agent jar. No update is necessary.
Expanded the channel window size to 4MB
[02/21/22 12:09:13] [SSH] Starting agent process: cd "/home/jenkins" && java -Xmx1048m -jar remoting.jar -workDir /home/jenkins -jar-cache /home/jenkins/remoting/jarCache
```

**Comment by sxa** [comment]
Build on Saturday on `-2` also didn't get to completion:
```
[](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/9/console#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/9/console#)17:43:40  Archiving artifacts
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
18:55:13  Execution error: java.io.IOException: Failed to extract /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/transfer of 10 files
[Pipeline] echo
18:55:13  java.io.IOException: Failed to extract /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-temurin/transfer of 10 files
18:55:13  	at hudson.FilePath.readFromTar(FilePath.java:2852)
18:55:13  	at hudson.FilePath.copyRecursiveTo(FilePath.java:2630)
18:55:13  	at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:70)
18:55:13  	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:257)
18:55:13  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
18:55:13  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
18:55:13  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
18:55:13  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:55:13  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:55:13  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:55:13  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:55:13  	at java.lang.Thread.run(Thread.java:748)
18:55:13  	Suppressed: java.util.concurrent.ExecutionException: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
18:55:13  		at hudson.remoting.Request$1.get(Request.java:323)
18:55:13  		at hudson.remoting.Request$1.get(Request.java:239)
18:55:13  		at hudson.remoting.FutureAdapter.get(FutureAdapter.java:64)
18:55:13  		at hudson.FilePath.copyRecursiveTo(FilePath.java:2633)
18:55:13  		... 10 more
18:55:13  	Caused by: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
18:55:13  		at hudson.remoting.Request.abort(Request.java:344)
18:55:13  		at hudson.remoting.Channel.terminate(Channel.java:1085)
18:55:13  		at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:94)
18:55:13  	Caused by: java.io.IOException: Unexpected EOF
18:55:13  		at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
18:55:13  		at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
18:55:13  		at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
18:55:13  		at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
18:55:13  Caused by: java.io.IOException: java.io.IOException: Unexpected EOF
18:55:13  	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:170)
18:55:13  	at hudson.util.HeadBufferingStream.read(HeadBufferingStream.java:61)
18:55:13  	at com.jcraft.jzlib.InflaterInputStream.fill(InflaterInputStream.java:175)
18:55:13  	at com.jcraft.jzlib.InflaterInputStream.read(InflaterInputStream.java:106)
18:55:13  	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:639)
18:55:13  	at java.io.InputStream.read(InputStream.java:101)
18:55:13  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1158)
18:55:13  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:878)
18:55:13  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1135)
18:55:13  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:854)
18:55:13  	at hudson.util.IOUtils.copy(IOUtils.java:43)
18:55:13  	at hudson.FilePath.readFromTar(FilePath.java:2842)
18:55:13  	... 11 more
```

**Comment by sxa** [comment]
[`-1` has wobbled again](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/log):
```
Agent successfully connected and online
Feb 21, 2022 11:14:46 AM org.eclipse.jgit.internal.storage.file.FileRepository <init>
SEVERE: Cannot read file /home/jenkins/.config/jgit/config
org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /home/jenkins/.config/jgit/config
	at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:186)
```

**Comment by aixtools** [comment]
- I hope this is not a file-encoding issue. I read somewhere (re: openj9 iirc) that were breaking some tests on AIX.
- I'll reach out in slack for additional info for triage.

**Comment by aixtools** [comment]
After that last wobble: seems to be looking good:
![image](https://user-images.githubusercontent.com/10852597/155985588-04d5e041-eb86-429c-8ea1-491565547664.png)

**Comment by aixtools** [comment]
I went and actually looked at the file getting the complaints: `~jenkins/.config/jgit/config`

And I do not understand what I am actually seeing - and in any case the info in build-1,2 looks suspicious.

```
root@nim.bak:[/home/root]dsh-adopt.ksh cat -n ~jenkins/.config/jgit/config
adopt01:
     1  /*
     2   * Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
     3   * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
     4   *
     5   * This code is free software; you can redistribute it and/or modify it
     6   * under the terms of the GNU General Public License version 2 only, as
     7   * published by the Free Software Foundation.
     8   *
     9   * This code is distributed in the hope that it will be useful, but WITHOUT
    10   * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    11   * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    12   * version 2 for more details (a copy is included in the LICENSE file that
    13   * accompanied this code).
    14   *
    15   * You should have received a copy of the GNU General Public License version
    16   * 2 along with this work; if not, write to the Free Software Foundation,
    17   * Inc., 51 Franklin St,==============
adopt02:
     1  /*
     2   * Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
     3   * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
     4   *
     5   * This code is free software; you can redistribute it and/or modify it
     6   * under the terms of the GNU General Public License version 2 only, as
     7   * published by the Free Software Foundation.
     8   *
     9   * This code is distributed in the hope that it will be useful, but WITHOUT
    10   * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    11   * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    12   * version 2 for more details (a copy is included in the LICENSE file that
    13   * accompanied this code).
    14   *
    15   * You should have received a copy of the GNU General Public License version
    16   * 2 along with this work; if not, write to the Free Software Foundation,
    17   * Inc., 51 Franklin St,==============
adopt03:
     1  [filesystem "IBM Corporation|1.8.0_241|/dev/hd1"]
     2          timestampResolution = 1005 milliseconds
     3          minRacyThreshold = 0 nanoseconds
==============
adopt04:
     1  [filesystem "power8-aix-host5.osuosl.org|Eclipse OpenJ9|1.8.0_242|/dev/hd1"]
     2          timestampResolution = 1001 microseconds
     3          minRacyThreshold = 8248 microseconds
     4  [filesystem "IBM Corporation|1.8.0_191|/dev/hd1"]
     5          timestampResolution = 1001 milliseconds
     6          minRacyThreshold = 0 nanoseconds
     7  [filesystem "IBM Corporation|1.8.0_261|/dev/hd1"]
     8          timestampResolution = 1001 milliseconds
     9          minRacyThreshold = 0 nanoseconds
==============
adopt05:
     1  [filesystem "IBM Corporation|1.8.0_261|/dev/hd1"]
     2          timestampResolution = 1002 milliseconds
     3          minRacyThreshold = 0 nanoseconds
     4  [filesystem "IBM Corporation|1.8.0_281|/dev/hd1"]
     5          timestampResolution = 1001 milliseconds
     6          minRacyThreshold = 0 nanoseconds
==============
adopt06:
     1  [filesystem "IBM Corporation|1.8.0_241|/dev/hd1"]
     2          timestampResolution = 1005 milliseconds
     3          minRacyThreshold = 0 nanoseconds
     4  [filesystem "IBM Corporation|1.8.0_261|/dev/hd1"]
     5          timestampResolution = 1001 milliseconds
     6          minRacyThreshold = 0 nanoseconds
     7  [filesystem "AdoptOpenJDK|1.8.0_292|/dev/hd1"]
     8          timestampResolution = 2001 microseconds
     9          minRacyThreshold = 5590 microseconds
==============
adopt07:
     1  [filesystem "IBM Corporation|1.8.0_241|/dev/hd1"]
     2          timestampResolution = 1001 milliseconds
     3          minRacyThreshold = 0 nanoseconds
==============
adopt08:
     1  [filesystem "IBM Corporation|1.8.0_241|/dev/hd1"]
     2          timestampResolution = 1001 milliseconds
     3          minRacyThreshold = 0 nanoseconds
==============
root@nim.bak:[/home/root]
```

**Comment by aixtools** [comment]
Any idea what the contents of this file should actually be?

Is it an idea to (re-)move a directory so these files are actually fetched again.

**Comment by aixtools** [comment]
Is this resolved (magically perhaps)?
