### ISSUE TITLE
jdk_net FAILED in Test_openjdk18_hs_extended.openjdk_aarch64_linux on test-docker* machines (aarch64)

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2514]

**Comment by sxa** [comment]
Related: #2894

**Comment by Haroon-Khel** [comment]
Nodes hosted on:

- dockerhost-equinix-ubuntu2204-armv8-1
  - https://ci.adoptium.net/job/Grinder/8726/console [test-docker-ubuntu2204-armv8-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Darmv8%2D2/)
  - https://ci.adoptium.net/job/Grinder/8728/console [test-docker-debain12-armv8l-1](https://ci.adoptium.net/computer/test%2Ddocker%2Ddebain12%2Darmv8l%2D1/)
  - https://ci.adoptium.net/job/Grinder/8729/console [test-docker-ubuntu2204-armv8-1](https://ci.adoptium.net/computer/test-docker-ubuntu2204-armv8-1)
  - https://ci.adoptium.net/job/Grinder/8731/console [test-docker-ubuntu2204-armv8-3](https://ci.adoptium.net/computer/test-docker-ubuntu2204-armv8-3)

- dockerhost-equinix-ubuntu2004-armv8-1
  - https://ci.adoptium.net/job/Grinder/8733/console [test-docker-ubuntu2204-armv8l-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Darmv8l%2D2/)
  - https://ci.adoptium.net/job/Grinder/8734/console [test-docker-ubuntu2004-armv8l-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv8l%2D2/)
  - https://ci.adoptium.net/job/Grinder/8735/console [test-docker-ubuntu2004-armv8l-3](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv8l%2D3/)
  - https://ci.adoptium.net/job/Grinder/8736/console [test-docker-ubuntu1804-armv8l-4](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu1804%2Darmv8l%2D4/)
  - https://ci.adoptium.net/job/Grinder/8743/console [test-docker-ubuntu2310-armv8l-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2310%2Darmv8l%2D1/)
  - https://ci.adoptium.net/job/Grinder/8744/console [test-docker-ubuntu2004-armv8l-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv8l%2D1/)

**Comment by Haroon-Khel** [comment]
Non intermittent failures:

test-docker-ubuntu2204-armv8-2

```
java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java.HttpURLConnectionExpectContinueTest

16:59:55  FINEST: ProxySelector Request for http://localhost:54321/
16:59:55  Feb 07, 2024 4:57:47 PM sun.net.www.protocol.http.HttpURLConnection plainConnect0
16:59:55  FINEST: Proxy used: DIRECT
16:59:55  Feb 07, 2024 4:57:47 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
16:59:55  FINE: sun.net.www.MessageHeader@402fb34410 pairs: {POST / HTTP/1.1: null}{Connection: Close}{Expect: 100-Continue}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/17.0.10}{Host: localhost:54321}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Content-type: application/x-www-form-urlencoded}{Transfer-Encoding: chunked}
16:59:55  java.net.SocketTimeoutException: Read timed out
16:59:55  	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
16:59:55  	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
16:59:55  	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
16:59:55  	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
```

**Comment by Haroon-Khel** [comment]
Non intermitent failures

Hosted on dockerhost-equinix-ubuntu2004-armv8-1

test-docker-ubuntu2204-armv8l-2

`java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java.HttpURLConnectionExpectContinueTest`
Same stack trace as above

```
java/net/Socket/Timeouts.java.Timeouts

16:37:55  WARNING: System::setSecurityManager will be removed in a future release
16:37:55  STDOUT:
16:37:55  test Timeouts.testBadTimeout1(): success
16:37:55  test Timeouts.testBadTimeout2(): success
16:37:55  test Timeouts.testTimedAccept1(): success
16:37:55  test Timeouts.testTimedAccept10(): success
16:37:55  test Timeouts.testTimedAccept11(): success
16:37:55  test Timeouts.testTimedAccept2(): success
16:37:55  test Timeouts.testTimedAccept3(): success
16:37:55  test Timeouts.testTimedAccept4(): success
16:37:55  test Timeouts.testTimedAccept5(): success
16:37:55  test Timeouts.testTimedAccept6(): success
16:37:55  test Timeouts.testTimedAccept7(): failure
16:37:55  java.lang.AssertionError: Duration 1805ms, expected >= 1900ms expected [true] but found [false]
16:37:55  	at org.testng.Assert.fail(Assert.java:99)
16:37:55  	at org.testng.Assert.failNotEquals(Assert.java:1037)
16:37:55  	at org.testng.Assert.assertTrue(Assert.java:45)
16:37:55  	at Timeouts.checkDuration(Timeouts.java:645)
16:37:55  	at Timeouts.testTimedAccept7(Timeouts.java:386)
```

test-docker-ubuntu2004-armv8l-2

`java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java.HttpURLConnectionExpectContinueTest`
Same stack trace as above


test-docker-ubuntu2004-armv8l-3

```
TEST: java/net/httpclient/Response204.java
TEST: java/net/httpclient/Response204V2Test.java
TEST: java/net/httpclient/RetryPost.java
TEST: java/net/httpclient/ThrowingSubscribersAsInputStream.java
TEST: java/net/httpclient/ThrowingPublishersInSubscribe.java
TEST: java/net/httpclient/websocket/PendingTextPongClose.java
TEST: java/net/httpclient/ThrowingPublishersInNextRequest.java
TEST: java/net/httpclient/ThrowingPushPromisesAsStringIO.java
TEST: java/net/httpclient/ShortResponseBodyGet.java
TEST: java/net/httpclient/ThrowingPublishersSanity.java
TEST: java/net/httpclient/ThrowingPublishersIOAfterCancel.java
TEST: java/net/httpclient/ThrowingSubscribersAsLines.java
TEST: java/net/httpclient/ThrowingPublishersCustomBeforeCancel.java
TEST: java/net/httpclient/SplitResponseSSL.java
TEST: java/net/httpclient/ThrowingSubscribersAsInputStreamAsync.java
TEST: java/net/httpclient/ShortResponseBodyPostWithRetry.java
TEST: java/net/httpclient/ThrowingPublishersCustomAfterCancel.java
TEST: java/net/httpclient/ThrowingPublishersIOBeforeCancel.java
TEST: java/net/httpclient/ThrowingPushPromisesAsStringCustom.java
TEST: java/net/httpclient/ShortResponseBodyPost.java
TEST: java/net/httpclient/ThrowingPushPromisesAsInputStreamIO.java
TEST: java/net/httpclient/ThrowingPushPromisesAsLinesCustom.java
TEST: java/net/httpclient/ProxySelectorTest.java
TEST: java/net/httpclient/ThrowingPushPromisesSanity.java
TEST: java/net/httpclient/SplitResponseSSLKeepAlive.java
TEST: java/net/httpclient/ThrowingPushPromisesAsInputStreamCustom.java
TEST: java/net/httpclient/ThrowingPublishersInRequest.java
TEST: java/net/httpclient/SmokeTest.java
TEST: java/net/httpclient/RedirectMethodChange.java
TEST: java/net/httpclient/ThrowingPushPromisesAsLinesIO.java
TEST: java/net/httpclient/ProxyAuthDisabledSchemesSSL.java
TEST: java/net/MulticastSocket/MulticastTTL.java
TEST: java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java
TEST: java/net/PortUnreachableException/Concurrent.java
TEST: java/net/NetworkInterface/IndexTest.java
```

**Comment by Haroon-Khel** [comment]
The common failure `java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java.HttpURLConnectionExpectContinueTest looks like it has an upstream issue `https://bugs.openjdk.org/browse/JDK-8314164
