### ISSUE TITLE
Jenkins agents on MacOS seem to fail when using anything other than JDK8

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2533]
Related https://github.com/adoptium/infrastructure/issues/2281

For the following machines, the jenkins agent failed to start when using jdk 16

test-macstadium-macos1014-x64-1
test-macstadium-macos1014-x64-2
test-macstadium-macos1014-x64-3

Error log:

```
Jul 19, 2021 5:21:30 P.M. jenkins.model.Jenkins <clinit>
SEVERE: Failed to load Jenkins.class
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
```

[It was found](https://github.com/adoptium/infrastructure/issues/2281#issuecomment-884083195) that making the agent use java 8 solves this error, and we do not yet know if this affects more than the 3 listed machines

Despite the title, we don't yet know if java 8 is the only jdk with which the jenkins agents do not fail, and we do not yet know if this issue persists on more than the 3 listed machines

**Comment by Haroon-Khel** [comment]
The jenkins agent for all of our MacOS machines are now using jdk17. Closing
