### ISSUE TITLE
System unavailable:  test-sxa-armv7l-ubuntu2004-odroid-1 

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2811]
When using "installer" to build Deb for armhf get failure:
```
hudson.remoting.ProxyException: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from cpc145836-warw19-2-0-cust71.3-2.cable.virginm.net/80.2.248.72:59076
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1194)
		at hudson.FilePath.act(FilePath.java:1183)
		at hudson.FilePath.mkdirs(FilePath.java:1374)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
hudson.remoting.ProxyException: java.nio.file.FileSystemException: /ssd/jenkins/workspace/adoptium-packages-linux-pipeline_new: Input/output error
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at hudson.FilePath.mkdirs(FilePath.java:3624)
	at hudson.FilePath.access$1100(FilePath.java:212)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1384)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1379)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3502)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:118)
	at java.base/java.lang.Thread.run(Unknown Source)
Finished: FAILURE

```

Made a test job to see if this node does have problem
when restrict to run on it, got the same error. but everything works on   test-sxa-armv7l-ubuntu2004-odroid-2
Since I do not have permission to offline node, need help to get the job not pick up this node and keep failing.

**Comment by sxa** [comment]
@Haroon-Khel has marked offline.
Machine appears to be having intermittent problems with its SSD.
