### ISSUE TITLE
'process apparently never started' build error on some aarch64 machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2834]
A build issue that we are seeing on one of our osuosl aarch64 systems, https://ci.adoptopenjdk.net/computer/build-osuosl-ubuntu2204-aarch64-1/

```
12:22:11  Checking out Revision 2ad4d503ba462dcebbba61563f39e2782d357281 (origin/master)
12:22:11   > git config remote.origin.url https://github.com/adoptium/ci-jenkins-pipelines.git # timeout=10
12:22:11   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
12:22:11   > git rev-parse origin/master^{commit} # timeout=10
12:22:11   > git config core.sparsecheckout # timeout=10
12:22:11   > git checkout -f 2ad4d503ba462dcebbba61563f39e2782d357281 # timeout=10
12:22:11  Commit message: "Fixed grammatical errors and updated outdated links in the feature_request.md (#475)"
[Pipeline] sh
12:27:29  process apparently never started in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-temurin@tmp/durable-e4b81918
12:27:29  (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
12:27:30  $ docker stop --time=1 b6638b4e1c6e4fd7acfb87bec791493128095a5ae62463b53d76ee3af19260c7
12:27:32  $ docker rm -f b6638b4e1c6e4fd7acfb87bec791493128095a5ae62463b53d76ee3af19260c7
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
12:27:32  Execution error: hudson.AbortException: script returned exit code -2
[Pipeline] echo
12:27:32  hudson.AbortException: script returned exit code -2
12:27:32  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)
12:27:32  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)
12:27:32  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)
12:27:32  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
12:27:32  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:27:32  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
12:27:32  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
12:27:32  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
12:27:32  	at java.base/java.lang.Thread.run(Thread.java:833)
```

That was from a jdk11 aarch64 temurin build, https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/142/console

https://github.com/adoptium/infrastructure/issues/2257 is related; the build failure appears in that issue on a centos8 aarch64 machine

**Comment by sxa** [comment]
Same when I try it on a ppc64le machine: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-temurin/146/

**Comment by sxa** [comment]
When I figured it out again I realised this was somethign I flagged years ago :-)

This occurs when the UID of the jenkins user does not match the UID in the docker container (1000). I've fixed it on the machine I was running on and it's now running properly at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-temurin/147/console

We could do with a solution that does not require the IDs to match.

**Comment by Haroon-Khel** [comment]
We are now seeing this on [dockerhost-skytap-ubuntu2204-ppc64le-1](https://ci.adoptopenjdk.net/computer/dockerhost-skytap-ubuntu2204-ppc64le-1/)
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk20/job/jdk20-linux-ppc64le-temurin/8/console

```
03:35:55  process apparently never started in /home/jenkins/workspace/build-scripts/jobs/jdk20/jdk20-linux-ppc64le-temurin@tmp/durable-ee94b5ca
03:35:55  (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
```

**Comment by Haroon-Khel** [comment]
Changed the UID of the jenkins user to 1000. Kicked off a build
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-temurin/165/console
Looks good so far

**Comment by Haroon-Khel** [comment]
> We could do with a solution that does not require the IDs to match.

My guess as to why this error is happening is due to the docker args

`13:04:36  $ docker run -t -d -u 1000:1001 -w ` (1000 is the UID, 1001 is the GID)

which I think comes from https://github.com/adoptium/infrastructure/blob/273d768fbdd657a7542512a0a75475fc98721482/ansible/docker/Dockerfile.CentOS6#L24

```
RUN groupadd -g 1000 ${user}
RUN useradd -c "Jenkins user" -d /home/${user} -u 1000 -g 1000 -m ${user}
```
If instead the UID and GID of the jenkins user on the host is passed in as a parameter, then it could look like 

RUN groupadd -g ${JenkinsGID} ${user}
RUN useradd -c "Jenkins user" -d /home/${user} -u ${JenkinsUID} -g ${JenkinsGID} -m ${user}

**Comment by Haroon-Khel** [comment]
I assume then that the error does not occur when the GID of the jenkins user does not match the GID in the container, since on dockerhost-skytap-ubuntu2004-ppc64le-1 the GID of the jenkins user is 1001

**Comment by Haroon-Khel** [comment]
This issue has been solved

**Comment by sxa** [comment]
@Haroon-Khel To be clear was the solution to [change the UID on the host](https://github.com/adoptium/infrastructure/issues/2834#issuecomment-1380318690) as per your earlier comment. If so, we'll need to look at mitigating this for the future since it's a manual step we've applied to the machine.
