### ISSUE TITLE
test-sxa-armv7l-ubuntu2004-odroid-1 unable to perform tests due to AccessDeniedException: /ssd/jenkins

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2867]
```
13:40:48  Running on [test-sxa-armv7l-ubuntu2004-odroid-1](https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1/) in /ssd/jenkins/workspace/Test_openjdk11_hs_sanity.perf_arm_linux
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] timeout
13:40:48  Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
13:40:48  ERROR: Execution failed
13:40:48  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from cpc145836-warw19-2-0-cust71.3-2.cable.virginm.net/80.2.248.72:38404
13:40:48  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
13:40:48  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
13:40:48  		at hudson.remoting.Channel.call(Channel.java:1000)
13:40:48  		at hudson.FilePath.act(FilePath.java:1194)
13:40:48  		at hudson.FilePath.act(FilePath.java:1183)
13:40:48  		at hudson.FilePath.mkdirs(FilePath.java:1374)
13:40:48  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
13:40:48  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
13:40:48  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:40:48  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
13:40:48  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:40:48  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13:40:48  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
13:40:48  		at java.base/java.lang.Thread.run(Thread.java:833)
13:40:48  java.nio.file.AccessDeniedException: /ssd/jenkins
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? any test job landing on that machine
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
- **Hyperlink** to re-run in Grinder: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_arm_linux/286 
- Is there an existing issue elsewhere covering this? https://github.com/adoptium/infrastructure/issues/2811 seems similar (intermittent ssd failures)
- Which machine(s) does it work on? This is the only machine currently online with https://ci.adoptopenjdk.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf/ labels
- Which machine(s) does it fail on? test-sxa-armv7l-ubuntu2004-odroid-1

Any other details:
I may as well mark this machine offline, however that will cause arm32 perf tests to fail/abort, since there are no other machines with ci.role.perf.

**Comment by sxa** [comment]
> arking this machine offline, however that will cause arm32 perf tests to fail/abort, since there are no other machines with ci.role.perf.

https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-2/ should be suitable - or have I missed a reason why this can only be run on `-1`?

**Comment by smlambert** [comment]
Another example from Jan 5th nightly runs: 
[Test_openjdk11_hs_sanity.perf_arm_linux/292](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_arm_linux/292) 
Running on [test-sxa-armv7l-ubuntu2004-odroid-1](https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1/)

```
13:34:06  ERROR: Execution failed
13:34:06  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from cpc145836-warw19-2-0-cust71.3-2.cable.virginm.net/80.2.248.72:55250
13:34:06  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
13:34:06  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
13:34:06  		at hudson.remoting.Channel.call(Channel.java:1000)
13:34:06  		at hudson.FilePath.act(FilePath.java:1194)
13:34:06  		at hudson.FilePath.act(FilePath.java:1183)
13:34:06  		at hudson.FilePath.mkdirs(FilePath.java:1374)
13:34:06  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
13:34:06  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
13:34:06  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:34:06  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
13:34:06  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:34:06  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13:34:06  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
13:34:06  		at java.base/java.lang.Thread.run(Thread.java:833)
13:34:06  java.nio.file.AccessDeniedException: /ssd/jenkins
```

**Comment by sxa** [comment]
> Another example from Jan 5th nightly runs: 

Hmmm I thought you'd marked it offline when you raised this - was it brought back intentionally? I've marked it offline again.

Is there a reason the perf tests wouldn't run on `-2` correctly that you know of?

**Comment by smlambert** [comment]
I do not know of any reason, except if it does not have ci.role.perf label

**Comment by sxa** [comment]
> I do not know of any reason, except if it does not have ci.role.perf label

I feel I'm missing something - https://ci.adoptopenjdk.net/computer/test%2Dsxa%2Darmv7l%2Dubuntu2004%2Dodroid%2D2/ definitely has `ci.role.perf` on it.

**Comment by sxa** [comment]
I've got `-1` back with the SSD - will need to see if it loses the connection at some point again.  I'll keep this open regardless as a reminder to check on it to see how long it stays active for.

**Comment by smlambert** [comment]
You are not missing anything, at the time this issue was created, -1 was the only perf labelled machine online, that must no longer be the case.
