### ISSUE TITLE
java/lang/ProcessHandle/InfoTest.java in jdk_lang fails on test-docker-centos8-x64-2

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2886]
java/lang/ProcessHandle/InfoTest.java in jdk_lang fails on test-docker-centos8-x64-2 with `java.lang.AssertionError: Command: expected: 'sleep', actual: /usr/bin/coreutils expected [true] but found [false]`

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk, TARGET=jdk_lang
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_linux/264/
- **Hyperlink** to re-run in Grinder:  [rerun Link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_lang_0,jdk_lang_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk17u%2Fjdk17u-release-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-17.0.6%2B8_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=1&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? all other ci.role.test&&hw.arch.x86&&sw.os.linux except test-docker-centos8-x64-2 
- Which machine(s) does it fail on? test-docker-centos8-x64-2

```
12:50:03  test InfoTest.test3(): failure
12:50:03  java.lang.AssertionError: Command: expected: 'sleep', actual: /usr/bin/coreutils expected [true] but found [false]
12:50:03  	at org.testng.Assert.fail(Assert.java:99)
12:50:03  	at org.testng.Assert.failNotEquals(Assert.java:1037)
12:50:03  	at org.testng.Assert.assertTrue(Assert.java:45)
12:50:03  	at InfoTest.test3(InfoTest.java:309)
12:50:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:50:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
12:50:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:50:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
12:50:03  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
12:50:03  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
12:50:03  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
12:50:03  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
12:50:03  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
12:50:03  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
12:50:03  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
12:50:03  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
12:50:03  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
12:50:03  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
12:50:03  	at org.testng.TestRunner.run(TestRunner.java:585)
12:50:03  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
12:50:03  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
12:50:03  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
12:50:03  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
12:50:03  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
12:50:03  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
12:50:03  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
12:50:03  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
12:50:03  	at org.testng.TestNG.runSuites(TestNG.java:1069)
12:50:03  	at org.testng.TestNG.run(TestNG.java:1037)
12:50:03  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
12:50:03  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
12:50:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:50:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
12:50:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:50:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
12:50:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:50:03  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Test Info**
Test Name: jdk_lang_0
Test Duration: 18 min 30 sec
Machine: test-docker-centos8-x64-2
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63c48eb7ed0b30773bb0d66f

**Build Info**
Build Name: Test_openjdk17_hs_sanity.openjdk_x86-64_linux
Jenkins Build start time: Jan 15 2023, 12:36 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_linux/264/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63c48defed0b30773bb0d3de

**Java Version**
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+8 (build 17.0.6+8)
OpenJDK 64-Bit Server VM Temurin-17.0.6+8 (build 17.0.6+8, mixed mode, sharing)

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_lang_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk17u%2Fjdk17u-release-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-17.0.6%2B8_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=1&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by Haroon-Khel** [comment]
If im reading the output right, it is expecting to find `coreutils`?

In test-docker-centos8-x64-2
```
[root@6970e9fbf0aa ~]# which coreutils
/usr/bin/coreutils
```
```
[root@6970e9fbf0aa ~]# which sleep
/usr/bin/sleep
```

**Comment by Haroon-Khel** [comment]
Related https://github.com/clearlinux/distribution/issues/1142

**Comment by Haroon-Khel** [comment]
Rerunning 
https://ci.adoptopenjdk.net/job/Grinder/6343/console

**Comment by Haroon-Khel** [comment]
Taking https://ci.adoptopenjdk.net/computer/test-docker-centos8-x64-2/ offline until after release

**Comment by sxa** [comment]
Since CentOS8 is no longer supported, the correct action here is to decomission that system in preference for any avaiable UBI/RHEL8 systems

**Comment by Haroon-Khel** [comment]
Running on ubi8 machines

https://ci.adoptium.net/job/Grinder/8749/console [test-docker-ubi8-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/8750/console [test-docker-ubi8-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D2/)

**Comment by sxa** [comment]
Noting that CentOS and UBI containers seem to use coreutils by default, RHEL and Fedora do not.
@Haroon-Khel Do you recall the result of the two UBI Grinders above?

**Comment by jiekang** [comment]
For any interested parties, an upstream fix with a special case for these environments can be done here:

https://github.com/openjdk/jdk/blob/5f2a92d954ce485d372c3cb3e5118556b1d076c3/test/jdk/java/lang/ProcessHandle/InfoTest.java#L294

**Comment by sxa** [comment]
Adjusted title so I recognise which issue this is ;-)
