### ISSUE TITLE
jdk_other com/sun/jndi/ldap/LdapPoolTimeoutTest.java failure on skytap ppc64le machine

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2924]
This was not part of the initial set that were failing, so I'm splitting this out into a separate issue:

              jdk_other com/sun/jndi/ldap/LdapPoolTimeoutTest.java failed on test-skytap-ubuntu2004-ppc64le-1 passed on others https://trss.adoptium.net/deepHistory?testId=62b783ac250c3c428c3aaebc

_Originally posted by @sophia-guo in https://github.com/adoptium/infrastructure/issues/2355#issuecomment-1167781399_

**Comment by Haroon-Khel** [comment]
According to https://github.com/adoptium/infrastructure/issues/2355#issuecomment-943522192 this is JDK17

**Comment by Haroon-Khel** [comment]
Rerunning the test on test-skytap-ubuntu2004-ppc64le-1 10 iterations https://ci.adoptium.net/job/Grinder/12033/console

**Comment by Haroon-Khel** [comment]
Still failing

```
13:54:44  configuration:
13:54:44  Boot Layer
13:54:44    add modules: java.naming
13:54:44  
13:54:44  STDOUT:
13:54:44  java.lang.AssertionError: expected [true] but found [false]
13:54:44  	at org.testng.Assert.fail(Assert.java:99)
13:54:44  	at org.testng.Assert.failNotEquals(Assert.java:1037)
13:54:44  	at org.testng.Assert.assertTrue(Assert.java:45)
13:54:44  	at org.testng.Assert.assertTrue(Assert.java:55)
13:54:44  	at LdapPoolTimeoutTest.attemptConnect(LdapPoolTimeoutTest.java:126)
13:54:44  	at LdapPoolTimeoutTest.lambda$test$0(LdapPoolTimeoutTest.java:92)
13:54:44  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:54:44  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13:54:44  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
```
