### ISSUE TITLE
AIX build is fails with Cannot run program "git" 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2936]
```
[2023-02-12T12:05:48.240Z] Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin"): error=0, Failed to exec spawn helper: pid: 14483504, exit value: 127
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[2023-02-12T12:05:48.240Z] 	at hudson.Proc$LocalProc.<init>(Proc.java:254)
[2023-02-12T12:05:48.240Z] 	at hudson.Proc$LocalProc.<init>(Proc.java:223)
[2023-02-12T12:05:48.240Z] 	at hudson.Launcher$LocalLauncher.launch(Launcher.java:997)
[2023-02-12T12:05:48.240Z] 	at hudson.Launcher$ProcStarter.start(Launcher.java:509)
[2023-02-12T12:05:48.240Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2668)
[2023-02-12T12:05:48.240Z] 	... 15 more
[2023-02-12T12:05:48.240Z] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 14483504, exit value: 127
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[2023-02-12T12:05:48.240Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[2023-02-12T12:05:48.240Z] 	... 21 more
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
   - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/194/

- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? [build-osuosl-aix71-ppc64-2](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2) - see https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/189/ 
- Which machine(s) does it fail on? [build-osuosl-aix71-ppc64-1](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1)

Any other details:

<img width="267" alt="Screen Shot 2023-02-14 at 5 35 17 PM" src="https://user-images.githubusercontent.com/2836948/218878755-127345c2-7fe5-4df4-8c42-f8ff07089692.png">

**Comment by sxa** [comment]
See also https://github.com/adoptium/infrastructure/issues/2922 which is an issue relating to the other build system being down, so we currently have no AIX7.1 build capability.

**Comment by steelhead31** [comment]
The issue with Git has been resolved, an unusual caching error in jenkins, resulted in the agent not being able to write to its workspace. A complete disconnect and reconnect of the agent, has allowed the build to success on this node.  
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/200/
