### ISSUE TITLE
System unavailable: build-azure-win2016-x64-1 needed for Windows Aarch64 build

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2990]
- Please put the system name in the title of this issue.
build-azure-win2016-x64-1

- Link to any log file showing the problem: 
https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk20/job/jdk20-evaluation-windows-aarch64-temurin/

- Please describe the issue:
jdk20 Windows aarch64 needs to run on "win2016" : https://github.com/adoptium/ci-jenkins-pipelines/blob/d8615aeb7bbb74e0560eacb550a4a644b678458d/pipelines/jobs/configurations/jdk20_pipeline_config.groovy#L161
This node is the only win2016 node.

**Comment by gdams** [comment]
I think the issue here is that the windows aarch64 node isn't setup to start Jenkins as a service. I'll dig into this later. I'll also kick off the process of provisioning a second machine for redundancy

**Comment by Haroon-Khel** [comment]
@andrew-m-leonard The machine is back online (thanks George). In the linked job, I see that smoke tests are also failing

```
11:19:16  PASSED: testShenandoahAvailable
11:19:16  FAILED: testZGCAvailable
11:19:16  java.lang.AssertionError: Expected ZGC to be absent but it is present. expected [true] but found [false]
11:19:16  	at org.testng.Assert.fail(Assert.java:96)
11:19:16  	at org.testng.Assert.failNotEquals(Assert.java:776)
11:19:16  	at org.testng.Assert.assertTrue(Assert.java:44)
11:19:16  	at net.adoptium.test.FeatureTests.testZGCAvailable(FeatureTests.java:151)
```
Is this being addressed somewhere?

**Comment by gdams** [comment]
> @andrew-m-leonard The machine is back online (thanks George). In the linked job, I see that smoke tests are also failing
> 
> ```
> 11:19:16  PASSED: testShenandoahAvailable
> 11:19:16  FAILED: testZGCAvailable
> 11:19:16  java.lang.AssertionError: Expected ZGC to be absent but it is present. expected [true] but found [false]
> 11:19:16  	at org.testng.Assert.fail(Assert.java:96)
> 11:19:16  	at org.testng.Assert.failNotEquals(Assert.java:776)
> 11:19:16  	at org.testng.Assert.assertTrue(Assert.java:44)
> 11:19:16  	at net.adoptium.test.FeatureTests.testZGCAvailable(FeatureTests.java:151)
> ```
> 
> Is this being addressed somewhere?

Not by me, I guess we need to work out if ZGC should be present or not? CC @smlambert

**Comment by Haroon-Khel** [comment]
I'm a bit confused, the linked job is for aarch64 yet it's running on an x64 machine?

**Comment by gdams** [comment]
> Not by me, I guess we need to work out if ZGC should be present or not? CC @smlambert

Ignore this, I've spotted the issue - find the test fix here: https://github.com/adoptium/temurin-build/pull/3281
