### ISSUE TITLE
Jenkins azurebuild dynamic agent is failing to provision

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3015]
Currently alpine-linux builds are hanging indefinitely due to no node being available, as the Azurebuild dynamic agent fails to provision nodes:
```
java.io.IOException: Agent failed to connect, even though the launcher didn't report it. See the log output for details.
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:326)
Caused: java.util.concurrent.ExecutionException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:860)
Caused: com.microsoft.azure.vmagent.exceptions.AzureCloudException
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:54)
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:33)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:889)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:812)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

To resolve the possiblility of alpine-linux jobs hanging builds indefinitely, the following node now as alpine-linux label on it:
```
dockerhost-equinix-ubuntu2204-x64-1
```

**Comment by andrew-m-leonard** [comment]
Dup of: https://github.com/adoptium/infrastructure/issues/2988

**Comment by sxa** [comment]
Beat me to it :-)
