### ISSUE TITLE
Tests failing in containerised arm32 environments JDK8

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3043]
I dont think this is a complete list, but just an observed list of failures from the recent April release. https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1525349302

jdk_instrument_2
jdk_net_2
jdk_util_2
jdk_jfr_2
jdk_other_2

These tests pass on the odroid machines, test-sxa-armv7l-ubuntu2004-odroid-1 and 2

**Comment by smlambert** [comment]
jdk_util, jdk_jfr failures seen in Jan 2024 release too (see notes [here](https://github.com/adoptium/aqa-tests/issues/4984#issuecomment-1897527288))

**Comment by sxa** [comment]
I believe the `perf` suites are also in this category and should be understood/mitigated.

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/Grinder/9819/tapResults/ [test-docker-ubuntu2004-armv7l-3](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-3)
https://ci.adoptium.net/job/Grinder/9820/tapResults/ [test-docker-ubuntu2004-armv7l-2](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-2)
https://ci.adoptium.net/job/Grinder/9821/tapResults/ [test-docker-ubuntu2004-armv7l-6](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-6)
https://ci.adoptium.net/job/Grinder/9822/tapResults/ [test-docker-ubuntu2004-armv7l-5](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-5)
https://ci.adoptium.net/job/Grinder/9823/tapResults/ [test-docker-ubuntu2004-armv7l-4](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-4)
https://ci.adoptium.net/job/Grinder/9824/tapResults/ [test-docker-ubuntu2004-armv7l-1](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-1)

Looks like jdk_other_2 jdk_security3_2 and jdk_instrument_2 pass on some machines and fail on others. Could be intermittent, im rerunning these tests on the same machines to confirm this. The jdk_net_2 jdk_util_2 and jdk_jfr_2 consistently fail.

The jfr failures are mostly SIGBUS errors

```
[thread -754977696 also had an error]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0xf63a91a8, pid=88505, tid=0xd34e8460
#
# JRE version: OpenJDK Runtime Environment (8.0_412-b08) (build 1.8.0_412-b08)
# Java VM: OpenJDK Client VM (25.412-b08 mixed mode linux-aarch32 )
# Problematic frame:
# V  [libjvm.so+0x33b1a8]  write_checkpoint_header(unsigned char*, long long, long long, bool, unsigned int)+0xe8
#
# Core dump written. Default location: /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17144060076039/jdk_jfr_2/work/scratch/0/core or core.88505
#
# An error report file with more information is saved as:
# /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17144060076039/jdk_jfr_2/work/scratch/0/hs_err_pid88505.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**java/net/Inet6Address/B6206527.java.B6206527** error log

```
trying LL addr: /fe80:0:0:0:42:acff:fe11:3%eth0
trying LL addr: /fe80:0:0:0:42:acff:fe11:3
java.net.BindException: Cannot assign requested address (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.bind(ServerSocket.java:344)
	at B6206527.main(B6206527.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.net.BindException
JavaTest Message: shutting down test
```

**java/net/ipv6tests/B6521014.java.B6521014**

```
java.net.ConnectException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at B6521014.test1(B6521014.java:77)
	at B6521014.main(B6521014.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.net.ConnectException
JavaTest Message: shutting down test
```

**Comment by Haroon-Khel** [comment]
Added an arm32 debian static docker container to the inventory https://ci.adoptium.net/computer/test-docker-debian12-armv7l-1/, rerunning the failed tests on it 
https://ci.adoptium.net/job/Grinder/9835/console

**Comment by Haroon-Khel** [comment]
Looking at grinders 9828 to 9833, jdk_other_2 jdk_security3_2 and jdk_instrument_2 fail intermittently.

Of jdk_security3_2's failing tests, alot are unexpected exits from what looks like a passing test, https://ci.adoptium.net/job/Grinder/9828/tapResults/ for example 

```
Failed test cases: 
TEST: sun/security/ssl/ClientHandshaker/CipherSuiteOrder.java
TEST: sun/security/ssl/SSLSocketImpl/RejectClientRenego.java
Test results: passed: 614; failed: 2 
```

**sun/security/ssl/ClientHandshaker/CipherSuiteOrder.java**

```
Unexpected exit from test [exit code: 134]    
Standard Output
server enabled suites: 
=====================

client enabled suites: 
======================
SSL_RSA_WITH_DES_CBC_SHA
SSL_RSA_WITH_RC4_128_MD5
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
SSL_RSA_WITH_RC4_128_SHA
SSL_DHE_DSS_WITH_DES_CBC_SHA

SSL_DHE_DSS_WITH_DES_CBC_SHA
SSL_RSA_WITH_RC4_128_MD5

Server read: 80
Cipher suite in use: SSL_RSA_WITH_RC4_128_MD5
client read: 85
    
Standard Error
STATUS:Passed.
```

**sun/security/ssl/SSLSocketImpl/RejectClientRenego.java**

```
Unexpected exit from test [exit code: 133]    
Standard Output
Session: Session(1714476936531|TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA)
Seen handshake completed #1
sending/receiving data, iteration: 0
starting new handshake
Got the expected exception
Got the expected exception
    
Standard Error
STATUS:Passed.
```

**Comment by sxa** [comment]
As part of the work we're having to do for [Ubuntu 24.04 support](https://github.com/adoptium/infrastructure/issues/3501) it would be useful to test whether an Ubuntu 24.04 at OSUOSL can run 32-bit containers without the same problems.

**Comment by Haroon-Khel** [comment]
Got a ubuntu 2404 arm32 container, https://ci.adoptium.net/computer/test-docker-ubuntu2404-armv7-1/, running on a ubuntu 2404 arm64 dockerhost machine https://ci.adoptium.net/computer/dockerhost-osuosl-ubuntu2404-aarch64-1/ (used to be dockerhost-osuosl-ubuntu2204-aarch64-1)

https://ci.adoptium.net/job/AQA_Test_Pipeline/258/console

**Comment by Haroon-Khel** [comment]
Failures

**sanity openjdk**

sun/security/krb5/auto/rcache_usemd5.sh

**extended openjdk**

jdk_beans_2
java/net/Inet6Address/B6206527.java
java/net/ipv6tests/B6521014.java
sun/security/ssl/SSLSocketImpl/ServerTimeout.java
jdk_jfr_2

**extended perf**

dacapo-xalan_0 (only one extended perf test failure. Perhaps their failures on containerised arm32 machines is intermittent?)

sanity functional, special functional and extended functional all failed. Rerunning

https://ci.adoptium.net/job/AQA_Test_Pipeline/259/console

**Comment by Haroon-Khel** [comment]
sanity special and extended (all functional) are failing to build due to this error

```
13:16:30      [javac] Compiling 1 source file to /home/jenkins/workspace/Test_openjdk8_hs_special.functional_arm_linux/aqa-tests/functional/MockitoTests/bin
13:16:31      [javac] /home/jenkins/workspace/Test_openjdk8_hs_special.functional_arm_linux/aqa-tests/functional/MockitoTests/src/test/java/MockitoMockTest.java:17: error: cannot access Mockito
13:16:31      [javac] import org.mockito.Mockito;
13:16:31      [javac]                   ^
13:16:31      [javac]   bad class file: /home/jenkins/testDependency/lib/mockito-core.jar(org/mockito/Mockito.class)
13:16:31      [javac]     class file has wrong version 55.0, should be 52.0
13:16:31      [javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```
The node uses jdk17 for its jenkins agent while these are jdk8 tests, that might have something to do with it

**Comment by Haroon-Khel** [comment]
No problem building jdk11 sanity functional tests https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.functional_arm_linux/420/console

**Comment by Haroon-Khel** [comment]
Rebuild of sanity special and extended (all functional)

**Comment by llxia** [comment]
re https://github.com/adoptium/infrastructure/issues/3043#issuecomment-2115123748, `class file has wrong version 55.0, should be 52.0` means mismatch java compiler. (see https://stackoverflow.com/questions/60612488/error-class-file-has-wrong-version-55-0-should-be-52-0-when-building-alfresco)

That being said, MockitoMockTest is set JDK11+ in playlist.xml AQA repo atm. 

Two things need to be done:
- https://ci.adoptium.net/job/Test_openjdk8_hs_extended.functional_arm_linux/ need to set  `DYNAMIC_COMPILE=true`
- MockitoMockTest needs to update its build.xml to only compile for JDK11+ (matching with its playlist.xml) - @sophiaxu0424 please update the build.xml.

**Comment by Haroon-Khel** [comment]
Rerunning the non intermittent failing tests jdk_net_2,jdk_util_2,jdk_jfr_2 on the newly created test-osuosl-ubuntu2404-aarch64-1

https://ci.adoptium.net/job/Grinder/10135/console

**Comment by Haroon-Khel** [comment]
Interesting, only the following jdk8 jdk_net tests fail on test-osuosl-ubuntu2404-aarch64-1

```
TEST: sun/net/www/http/HttpClient/KeepAliveTest.java
TEST: sun/net/www/http/KeepAliveCache/B8291637.java
TEST: sun/net/www/http/KeepAliveCache/KeepAliveProperty.java
TEST: sun/net/www/http/KeepAliveCache/B8293562.java
```

**Comment by sxa** [comment]
I've [kicked off the sanity run on the U2404/arm32 box with the v1.0.1-release branch](https://ci.adoptium.net/job/Grinder/10165/console) to see if the build failure is specific to something in the master branch. It's not immediately obvious why this would be specific to arm32 machines though.

**Comment by Haroon-Khel** [comment]
jdk8 jdk_util tests, which consistently fail on the static docker arm32 nodes, pass on test-docker-ubuntu2404-armv7-1 

https://ci.adoptium.net/job/Grinder/10156/tapResults/

**Comment by Haroon-Khel** [comment]
> I believe the perf suites are also in this category and should be understood/mitigated so the CI is not dependent upon my ODROID systems.

@sxa Which were the failing perf tests again? https://ci.adoptium.net/job/AQA_Test_Pipeline/280/console (jdk8 v1.0.1-release branch on est-docker-ubuntu2404-armv7-1) finished running. Sanity perf and extended perf both passed

https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.perf_arm_linux/475/
https://ci.adoptium.net/job/Test_openjdk8_hs_extended.perf_arm_linux/137/

**Comment by sxa** [comment]
> @sxa Which were the failing perf tests again? https://ci.adoptium.net/job/AQA_Test_Pipeline/280/console (jdk8 v1.0.1-release branch on est-docker-ubuntu2404-armv7-1) finished running. Sanity perf and extended perf both passed

Can't remember which versions, but we should perhaps try running those on the Equinix containers and see if they pass there

**Comment by Haroon-Khel** [comment]
I kicked off JDK8 11 21 sanity and extended perf tests on the static docker arm32 nodes but I think because I kicked too many at once, the earlier test jobs did not get saved, leaving the earlier AQA pipelines looking like this https://ci.adoptium.net/job/AQA_Test_Pipeline/316/console 

```
[Pipeline] }
Failed in branch Test_openjdk17_hs_extended.perf_arm_linux_6
[Pipeline] }
Failed in branch Test_openjdk11_hs_extended.perf_arm_linux_4
[Pipeline] }
Failed in branch Test_openjdk8_hs_sanity.perf_arm_linux_1
[Pipeline] }
Failed in branch Test_openjdk17_hs_sanity.perf_arm_linux_5
[Pipeline] }
Failed in branch Test_openjdk8_hs_extended.perf_arm_linux_2
[Pipeline] }
Failed in branch Test_openjdk11_hs_sanity.perf_arm_linux_3
[Pipeline] // parallel
[Pipeline] End of Pipeline
```
But if you look at the last 5 jobs (the only ones available) in 
https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.perf_arm_linux/
https://ci.adoptium.net/job/Test_openjdk8_hs_extended.perf_arm_linux/
https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.perf_arm_linux/
https://ci.adoptium.net/job/Test_openjdk11_hs_extended.perf_arm_linux/
https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.perf_arm_linux/
https://ci.adoptium.net/job/Test_openjdk21_hs_extended.perf_arm_linux/

We are seeing them pass on static docker containers, which at the very least reduces our dependency on the odroid machines. https://ci.adoptium.net/job/Test_openjdk8_hs_extended.perf_arm_linux/ has the lowest pass rate, so some further investigation is required there

**Comment by sxa** [comment]
Maybe also test with a JDK11 using the jdk8u material (or see if there is an equivalent test in the jdk11u repo)

**Comment by Haroon-Khel** [comment]
Looking at https://github.com/adoptium/infrastructure/issues/3043#issuecomment-2194526343, it seems the perf tests pass intermittently on the static docker nodes. I wouldnt recommend shutting the odroid nodes off but atleast we know we can rely on our static containers for these tests

**Comment by Haroon-Khel** [comment]
Im going to rerun the test failures mentioned in https://github.com/adoptium/infrastructure/issues/3043#issue-1688845949 on static arm32 boxes and the odroid machines. According to https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1525349302 we should see a difference in pass/fail between odroid and static docker containers

https://ci.adoptium.net/job/Grinder/12721/console test-docker-ubuntu2404-armv7-7
https://ci.adoptium.net/job/Grinder/12722/console test-docker-debian12-armv7l-1
https://ci.adoptium.net/job/Grinder/12723/console test-docker-ubuntu2404-armv7-5
https://ci.adoptium.net/job/Grinder/12724/console test-docker-ubuntu2404-armv7-4
https://ci.adoptium.net/job/Grinder/12725/console test-docker-ubuntu2404-armv7-6
https://ci.adoptium.net/job/Grinder/12726/console test-docker-ubuntu2404-armv7-1
https://ci.adoptium.net/job/Grinder/12727/console test-docker-ubuntu2404-armv7-8
https://ci.adoptium.net/job/Grinder/12728/console test-docker-ubuntu2404-armv7-3
https://ci.adoptium.net/job/Grinder/12730/console **test-sxa-armv7l-ubuntu2004-odroid-2**

**Comment by Haroon-Khel** [comment]
From the above tests on the static ndoes a consistent failure is jdk_jfr_2. jdk_util_2 fails on most of the static nodes but passes on test-docker-ubuntu2404-armv7-1 it passes (this is hosted on dockerhost-osuosl-ubuntu2404-aarch64-1 while the other static arm32 nodes are hosted on dockerhost-equinix-ubuntu2204-armv8l-1 and dockerhost-equinix-ubuntu2404-armv8-1.

jdk_jfr_2 passes on the odroid machine. So jdk_jfr_2 is the only test target which passes only on odroid

**Comment by sxa** [comment]
Perhaps this is a good opportunity to move the arm32 containers onto OSUOSL hosts (although it's not exactly clear why they're only passing there!)

**Comment by Haroon-Khel** [comment]
@jiekang

**Comment by jiekang** [comment]
Common error log for the jdk_jfr test failures:
```
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] # A fatal error has been detected by the Java Runtime Environment:
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] #  SIGBUS (0x7) at pc=0xeec1ae94, pid=446741, tid=0xbbcb6420
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] # JRE version: OpenJDK Runtime Environment (8.0_442-b06) (build 1.8.0_442-b06)
[2025-03-03T16:50:03.557Z] # Java VM: OpenJDK Client VM (25.442-b06 mixed mode linux-aarch32 )
[2025-03-03T16:50:03.557Z] # Problematic frame:
[2025-03-03T16:50:03.557Z] # V  [libjvm.so+0x33ae94]  write_checkpoint_header(unsigned char*, long long, long long, bool, unsigned int)+0xe8
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] # Core dump written. Default location: /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17410041514692/jdk_jfr_2/work/scratch/2/core or core.446741
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] # An error report file with more information is saved as:
[2025-03-03T16:50:03.557Z] # /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17410041514692/jdk_jfr_2/work/scratch/2/hs_err_pid446741.log
[2025-03-03T16:50:03.557Z] #
[2025-03-03T16:50:03.557Z] # If you would like to submit a bug report, please visit:
[2025-03-03T16:50:03.557Z] #   https://github.com/adoptium/adoptium-support/issues
[2025-03-03T16:50:03.557Z] #
```

**Comment by Haroon-Khel** [comment]
Rerunning jdk_jfr_2 for JDK11

https://ci.adoptium.net/job/Grinder/12753/console test-docker-ubuntu2404-armv7-7
https://ci.adoptium.net/job/Grinder/12754/console test-docker-debian12-armv7l-1
https://ci.adoptium.net/job/Grinder/12755/console test-docker-ubuntu2404-armv7-5
https://ci.adoptium.net/job/Grinder/12756/console test-docker-ubuntu2404-armv7-4
https://ci.adoptium.net/job/Grinder/12757/console test-docker-ubuntu2404-armv7-6
https://ci.adoptium.net/job/Grinder/12758/console test-docker-ubuntu2404-armv7-1
https://ci.adoptium.net/job/Grinder/12759/console test-docker-ubuntu2404-armv7-8
https://ci.adoptium.net/job/Grinder/12760/console test-docker-ubuntu2404-armv7-3

**Comment by Haroon-Khel** [comment]
Rerunning jdk_jfr_2 for JDK17

https://ci.adoptium.net/job/Grinder/12761/console test-docker-ubuntu2404-armv7-7
https://ci.adoptium.net/job/Grinder/12762/console test-docker-debian12-armv7l-1
https://ci.adoptium.net/job/Grinder/12763/console test-docker-ubuntu2404-armv7-5
https://ci.adoptium.net/job/Grinder/12764/console test-docker-ubuntu2404-armv7-4
https://ci.adoptium.net/job/Grinder/12765/console test-docker-ubuntu2404-armv7-6
https://ci.adoptium.net/job/Grinder/12766/console test-docker-ubuntu2404-armv7-1
https://ci.adoptium.net/job/Grinder/12767/console test-docker-ubuntu2404-armv7-8
https://ci.adoptium.net/job/Grinder/12768/console test-docker-ubuntu2404-armv7-3

**Comment by Haroon-Khel** [comment]
For JDK11 and 17 they all pass

**Comment by roberttoyonaga** [comment]
Just posting here in case. I believe the root cause for the JDK8 JFR failures on arm32 containers on arm64 machines is this: https://github.com/adoptium/aqa-tests/issues/3115#issuecomment-2256561374

Not sure why those tests are still running because they should be disabled (for eclipse at least): https://github.com/roberttoyonaga/aqa-tests/blob/a3953f83c4e420f3f71f3e40f3b46beca056f7e5/openjdk/playlist.xml#L1479

**Comment by smlambert** [comment]
> Not sure why those tests are still running because they should be disabled (for eclipse at least)

Why the disable functionality is 'not working'
https://github.com/adoptium/TKG/issues/682#issuecomment-2722435317

**Comment by smlambert** [comment]
@Haroon-Khel - One way to approach this is to modify the vendor string in the playlist disable statement to 'temurin'.  Its not great, but it should cause the disablement of this target to be applied for JDK8 test runs.

https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L1924
Change `<vendor>eclipse</vendor>` to `<vendor>temurin</vendor>`

**Comment by sxa** [comment]
We should perhaps test anything that's still outstanding on the new OSUOSL systems.

**Comment by sxa** [comment]
Noting that there were some failures that occurred on the July 2026 release cycle with JDK8 and they passed when run on the ODROID system:
- dacapo-xalan_0 
- java/util/concurrent/BlockingQueue/MultipleProducersSingleConsumerLoops.java

Ref: [Slack thread](https://adoptium.slack.com/archives/C5219G28G/p1785937141153469) and [arm32/jdk8 triage issue](https://github.com/adoptium/aqa-tests/issues/7476)

**Comment by sxa** [comment]
Upstream issue raised by Andrew with some analysis: https://bugs.openjdk.org/browse/JDK-8391660
