### ISSUE TITLE
`centos7_docker_image_updater` no longer working on Ubuntu 16.04/arm32

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3150]
See any recent run of https://ci.adoptium.net/job/centos7_docker_image_updater/ - this is currently preventing updates being pushed from the changes from new infrastructure PRs.
```
Collecting PyYAML
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpCjvVZY
       cwd: /tmp/pip-install-pzD55C/pyyaml
  Complete output (46 lines):
  running egg_info
  creating lib/PyYAML.egg-info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 295, in <module>
      python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 296, in run
      self.find_sources()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 303, in find_sources
      mm.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 534, in run
      self.add_defaults()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 570, in add_defaults
      sdist.add_defaults(self)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/py36compat.py", line 36, in add_defaults
      self._add_defaults_ext()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "setup.py", line 201, in get_source_files
      self.cython_sources(ext.sources, ext)
    File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
      raise AttributeError, attr
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpCjvVZY Check the logs for full command output.
The command '/bin/sh -c pip install ansible' returned a non-zero code: 1
```

**Comment by sxa** [comment]
Noting for reference that the last working run was https://ci.adoptium.net/job/centos7_docker_image_updater/350 which used:
```
Successfully installed pip-20.3.4 setuptools-44.1.1 wheel-0.37.1
Successfully installed cffi-1.15.1 cryptography-2.9.2 enum34-1.1.10 ipaddress-1.0.23 pycparser-2.21 six-1.16.0
MarkupSafe-1.1.1 PyYAML-5.4.1 ansible-4.10.0 ansible-core-2.11.12 jinja2-2.11.3 packaging-20.9 pyparsing-2.4.7 resolvelib-0.5.4
```

**Comment by sxa** [comment]
There was an issue `ERROR: docker login failed` in the run associated with this PR at https://ci.adoptium.net/job/centos7_docker_image_updater/357/console which caused C7/aarch64 to fail so I'm re-running at https://ci.adoptium.net/job/centos7_docker_image_updater/358/console to try and get this update out.
