### ISSUE TITLE
sanity.perf test failing on arm_linux on test-sxa-armv7l-ubuntu2004-odroid-1 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3177]
in /ssd/jenkins/workspace/Test_openjdk21_hs_sanity.perf_arm_linux

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? sanity.perf
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.perf_arm_linux/103/
- **Hyperlink** to re-run in Grinder: rerun [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.perf&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=test-sxa-armv7l-ubuntu2004-odroid-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk21%2Fjdk21-linux-arm-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21%2B35_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=perf&UPSTREAM_JOB_NUMBER=68&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? test-sxa-armv7l-ubuntu2004-odroid-2
- Which machine(s) does it fail on? test-sxa-armv7l-ubuntu2004-odroid-1

Any other details:
Console output:
```
19:49:37  Exception: java.nio.file.AccessDeniedException: /ssd/jenkins
[Pipeline] sh
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
19:49:37  ERROR: Execution failed
19:49:37  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from warw-19-b2-v4wan-165422-cust195.vm38.cable.virginm.net/82.12.92.196:60828
19:49:37  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
19:49:37  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
19:49:37  		at hudson.remoting.Channel.call(Channel.java:1000)
19:49:37  		at hudson.FilePath.act(FilePath.java:1192)
19:49:37  		at hudson.FilePath.act(FilePath.java:1181)
19:49:37  		at hudson.FilePath.mkdirs(FilePath.java:1372)
19:49:37  		at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.setupControlDir(FileMonitoringTask.java:307)
19:49:37  		at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.<init>(FileMonitoringTask.java:295)
19:49:37  		at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:280)
19:49:37  		at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:269)
19:49:37  		at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:139)
19:49:37  		at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:132)
19:49:37  		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:326)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
19:49:37  		at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
19:49:37  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:49:37  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:49:37  		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
19:49:37  		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
19:49:37  		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
19:49:37  		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
19:49:37  		at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
19:49:37  		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
19:49:37  		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
19:49:37  		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
19:49:37  		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
19:49:37  		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:163)
19:49:37  		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:148)
19:49:37  		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:178)
19:49:37  		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
19:49:37  		at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
19:49:37  		at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
19:49:37  		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
19:49:37  		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
19:49:37  		at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
19:49:37  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:49:37  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:49:37  		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
19:49:37  		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:110)
19:49:37  		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
19:49:37  		at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
19:49:37  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:49:37  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:49:37  		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
19:49:37  		at com.cloudbees.groovy.cps.impl.CastBlock$ContinuationImpl.cast(CastBlock.java:47)
19:49:37  		at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
19:49:37  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:49:37  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:49:37  		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
19:49:37  		at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
19:49:37  		at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
19:49:37  		at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
19:49:37  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:49:37  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:49:37  		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
19:49:37  		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
19:49:37  		at com.cloudbees.groovy.cps.Next.step(Next.java:83)
19:49:37  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
19:49:37  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
19:49:37  		at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
19:49:37  		at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
19:49:37  		at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
19:49:37  		at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
19:49:37  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:49:37  		at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
19:49:37  		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
19:49:37  		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
19:49:37  		at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
19:49:37  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
19:49:37  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:49:37  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
19:49:37  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
19:49:37  		at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by smlambert** [comment]
Any test job sent to this machine will fail, so will mark this machine offline until resolution of this issue.

**Comment by sxa** [comment]
Adjusting title as it's not specific to a test job and is an issue we've been aware of for a while.

**Comment by sxa** [comment]
Docker tags removed from this machine now that odroid-2 is working properly for docker again (Bus error messages resolved by upgrading docker from the defined package repository on the machine)

**Comment by sxa** [comment]
I might attempt an upgrade to [Ubuntu 22.04](https://wiki.odroid.com/odroid-xu4/os_images/linux/ubuntu_6.1/minimal/20230905) or [Ubuntu 24.04](https://wiki.odroid.com/odroid-xu4/os_images/linux/ubuntu_6.6/minimal/202409011)
