### ISSUE TITLE
Ansible: Installation Of Jenkins As Service Fails On Windows 2022 x64

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3290]
- Bug in ansible playbook

Details:

The installation of jenkins as a service fails on Windows Server 2022, and this element of the process needs fixing.

On Windows 2022, having the default paths set to c:\users\jenkins is not correct, and the jenkins user created by  the playbooks has permissions and access details on this path.

```
10:33:58  The recommended git tool is: git
10:34:02  No credentials specified
10:34:03  Cloning the remote Git repository
10:34:03  ERROR: Error cloning remote repo 'origin'
10:34:03  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
10:34:03  stdout: 
10:34:03  stderr: fatal: detected dubious ownership in repository at '/cygdrive/c/users/jenkins/workspace/Grinder/aqa-tests'
10:34:03  To add an exception for this directory, call:
10:34:03  
10:34:03  	git config --global --add safe.directory /cygdrive/c/users/jenkins/workspace/Grinder/aqa-tests
10:34:03  
10:34:03  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2842)
10:34:03  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
10:34:03  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)
10:34:03  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)
10:34:03  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)
10:34:03  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
10:34:03  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
10:34:03  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:34:03  	at hudson.remoting.Request$2.run(Request.java:377)
10:34:03  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:34:03  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:34:03  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:34:03  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:34:03  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
10:34:03  	at java.base/java.lang.Thread.run(Thread.java:840)
10:34:03  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 20.26.116.218/20.26.116.218:49889
10:34:03  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
10:34:03  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
10:34:03  		at hudson.remoting.Channel.call(Channel.java:1000)
10:34:03  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)
10:34:03  		at jdk.internal.reflect.GeneratedMethodAccessor719.invoke(Unknown Source)
10:34:03  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:34:03  		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:34:03  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)
10:34:03  		at jdk.proxy211/jdk.proxy211.$Proxy426.execute(Unknown Source)
10:34:03  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)
10:34:03  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
10:34:03  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
10:34:03  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
10:34:03  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
10:34:03  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
10:34:03  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
10:34:03  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:34:03  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:34:03  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:34:03  		... 1 more
[Pipeline] }
10:34:03  ERROR: Error cloning remote repo 'origin'
10:34:03  Retrying
```

**Comment by steelhead31** [comment]
This has now been corrected, issue was machine specific, test-azure-win2022-x64-3 did not encounter this issue, so closing.
