### ISSUE TITLE
java/time/test/java/time/format/TestUTCParse fails on macstadium machines (expects UTC not PST)

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3361]
As mentioned in https://github.com/adoptium/aqa-tests/issues/4982#issuecomment-1894967658 and https://github.com/adoptium/aqa-tests/issues/4982#issuecomment-1903640265, java/time/test/java/time/format/TestUTCParse fails with the following error:

```
11:29:41  test test.java.time.format.TestUTCParse.testUTCShortNameRoundTrip(): failure
11:29:41  java.lang.AssertionError: expected [UTC−08:00] but found [PST]
11:29:41  	at org.testng.Assert.fail(Assert.java:99)
11:29:41  	at org.testng.Assert.failNotEquals(Assert.java:1037)
11:29:41  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
11:29:41  	at org.testng.Assert.assertEquals(Assert.java:122)
11:29:41  	at org.testng.Assert.assertEquals(Assert.java:629)
11:29:41  	at org.testng.Assert.assertEquals(Assert.java:639)
11:29:41  	at test.java.time.format.TestUTCParse.testUTCShortNameRoundTrip(TestUTCParse.java:65)
11:29:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:29:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:29:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:29:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:29:41  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
11:29:41  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
11:29:41  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
11:29:41  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
11:29:41  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
11:29:41  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
11:29:41  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
11:29:41  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
11:29:41  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
11:29:41  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
11:29:41  	at org.testng.TestRunner.run(TestRunner.java:585)
11:29:41  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
11:29:41  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
11:29:41  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
11:29:41  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
11:29:41  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
11:29:41  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
11:29:41  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
11:29:41  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
11:29:41  	at org.testng.TestNG.runSuites(TestNG.java:1069)
11:29:41  	at org.testng.TestNG.run(TestNG.java:1037)
11:29:41  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
11:29:41  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
11:29:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:29:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:29:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:29:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:29:41  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:29:41  	at java.base/java.lang.Thread.run(Thread.java:829)
11:29:41  
11:29:41  ===============================================
11:29:41  java/time/test/java/time/format/TestUTCParse.java
11:29:41  Total tests run: 4, Passes: 3, Failures: 1, Skips: 0
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk, TARGET=jdk_custom, CUSTOM_TARGET=java/time/test/java/time/format/TestUTCParse.java
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_0/90/
- **Hyperlink** to re-run in Grinder: 
  - rerun [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=jdk_custom&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_hs_extended.openjdk_aarch64_mac&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=1&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=3&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.0-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-mac-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=java/time/test/java/time/format/TestUTCParse.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-11.0.22%2B7_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=96&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=16&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? orka agents
- Which machine(s) does it fail on? test-macstadium-macos11-arm64-2 (possibly others)

Any other details:
see console output above

**Comment by sxa** [comment]
Related: Top level issue at https://github.com/adoptium/infrastructure/issues/2662, and the orka issue at https://github.com/adoptium/infrastructure/issues/2536

**Comment by sxa** [comment]
Need to verify if this fails on the orka machines, and then decide what to do if it still fails on any of our existing statically provisiioned systems (e.g. macincloud)

**Comment by sxa** [comment]
Attempting re-run on the orka nodes at https://ci.adoptium.net/job/Grinder/11427/ but it fell foul of https://github.com/adoptium/infrastructure/issues/3814

**Comment by sxa** [comment]
Also testing on x64 at:
- [G#11429 on test-macstadium-1014](https://ci.adoptium.net/job/Grinder/11429/)
- [G#11430 on macincloud-1201-1](https://ci.adoptium.net/job/Grinder/11430/)
- [G#11431 on orka node](https://ci.adoptium.net/job/Grinder/11431)

**Comment by sxa** [comment]
Noting that this is the same failure which has been seen in https://github.com/adoptium/infrastructure/issues/3658#issuecomment-2210967471 and the test has been [excluded for Temurin runs](https://github.com/adoptium/aqa-tests/pull/5447). The notes in there also indicate that it's a test which has been removed from newer JDKs.

**Comment by Haroon-Khel** [comment]
iirc I excluded it on linux only as that was the platform I was running tests on. I think it should also be excluded on MacOS since it was agreed that the test itself does not handle timezones well

**Comment by Haroon-Khel** [comment]
Exclude pr https://github.com/adoptium/aqa-tests/pull/5766
