### ISSUE TITLE
jenkins: openpower-controller.osuosl.org: Name or service not known

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3487]
The following is happening about 144 times per day. Each instance generates about 50 lines of exception trace in the jenkins log so is therefore now a good proportion of the size of the logs :-)
```
java.net.UnknownHostException: openpower-controller.osuosl.org: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
[...]
	at org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:52)
[...]
```
This is the hostname referenced in the OSUOSL cloud configuration under the openstack plugin at https://ci.adoptium.net/manage/cloud/osuosl/

**Comment by sxa** [comment]
Node has changed to `openpower-openstack.osuosl.org` although the credential we're using no longer seems to be valid for that instance so I've set the credential to `None` for now in order to alleviate the log pollution. We'll need to decide whether to keep using this and acquire a suitable set of automation credentials, or delete the configuration. Noting that jenkins doesn't seem to provide a way to disable a particular cloud configuration, otherwise I would have done that instead.
