### ISSUE TITLE
java/nio/file/DirectoryStream/SecureDS.java fails on newer Alpine OSs

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3522]
`java/nio/file/DirectoryStream/SecureDS.java` fails for JDK17 x64 on our alpine 319 machines. Appeared in the April 2024 JDK17 aqa triage, https://github.com/adoptium/aqa-tests/issues/5231#issuecomment-2062885416. It passes on a [314 machine ](https://ci.adoptium.net/computer/test%2Ddocker%2Dalpine314%2Dx64%2D1/) https://ci.adoptium.net/job/Grinder/9688/console

```
java.lang.AssertionError: SecureDirectoryStream not supported.
	at SecureDS.main(SecureDS.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

At the moment we dont know the latest alpine OS on which it passes, only that it fails on 319 and passes on 314

Related failure on arm32 linux https://bugs.openjdk.org/browse/JDK-8214078

**Comment by steelhead31** [comment]
This may or may not be relevant.. https://bugs.openjdk.org/browse/JDK-8214078

**Comment by sxa** [comment]
Has been raised at https://bugs.openjdk.org/browse/JDK-8343450 - looks like the failure started between Alpine 3.18 and 3.19. User who raised that JBS has also raised https://gitlab.alpinelinux.org/alpine/aports/-/issues/16570 to query if anything in Alpine has chnaged
