### ISSUE TITLE
jdk_tools target fails on test-azure-ubuntu2404-x64-1 with IOException running dpkg

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3667]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? jdk_tools
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure 
  - https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2/14/
- **Hyperlink** to re-run in Grinder:  [Rerun link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=jdk_custom&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_hs_extended.openjdk_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=1&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.2-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk17u%2Fjdk17u-release-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=tools%2Fjpackage%2Flinux%2FAppAboutUrlTest.java%23id0+tools%2Fjpackage%2Flinux%2FAppCategoryTest.java+tools%2Fjpackage%2Flinux%2FLinuxBundleNameTest.java+tools%2Fjpackage%2Flinux%2FLinuxResourceTest.java+tools%2Fjpackage%2Flinux%2Fjdk%2Fjpackage%2Ftests%2FUsrTreeTest.java+tools%2Fjpackage%2Flinux%2FMaintainerTest.java+tools%2Fjpackage%2Flinux%2FPackageDepsTest.java+tools%2Fjpackage%2Flinux%2FReleaseTest.java+tools%2Fjpackage%2Flinux%2FShortcutHintTest.java%23id0+tools%2Fjpackage%2Fshare%2Fjdk%2Fjpackage%2Ftests%2FBasicTest.java+tools%2Fjpackage%2Fshare%2Fjdk%2Fjpackage%2Ftests%2FVendorTest.java%23id1+tools%2Fjpackage%2Fshare%2FAppImagePackageTest.java+tools%2Fjpackage%2Fshare%2FAddLauncherTest.java%23id1+tools%2Fjpackage%2Fshare%2FEmptyFolderPackageTest.java+tools%2Fjpackage%2Fshare%2FIconTest.java+tools%2Fjpackage%2Fshare%2FFileAssociationsTest.java%23id0+tools%2Fjpackage%2Fshare%2FInstallDirTest.java%23id0+tools%2Fjpackage%2Fshare%2FLicenseTest.java%23id1+tools%2Fjpackage%2Fshare%2FLicenseTest.java%23id0+tools%2Fjpackage%2Fshare%2FMultiLauncherTwoPhaseTest.java+tools%2Fjpackage%2Fshare%2FMultiNameTwoPhaseTest.java+tools%2Fjpackage%2Fshare%2FSimplePackageTest.java+tools%2Fjpackage%2Fshare%2FRuntimePackageTest.java%23id0&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-17.0.12%2B5_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=195&DOCKERIMAGE_TAG=&TEST_TIME=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=22&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? [test-aws-rhel8-x64-1](https://ci.adoptium.net/computer/test-aws-rhel8-x64-1) (See: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_rerun/16/ to see a passed run)
- Which machine(s) does it fail on? [test-azure-ubuntu2404-x64-1](https://ci.adoptium.net/computer/test-azure-ubuntu2404-x64-1)

Any other details:
https://github.com/adoptium/aqa-tests/issues/5436#issuecomment-2225678340

```
[13:24:13.527] java.io.IOException: Command [dpkg, -S, /lib/x86_64-linux-gnu/libbrotlidec.so.1] exited with 1 code
	at jdk.jpackage/jdk.jpackage.internal.Executor.executeExpectSuccess(Executor.java:90)
	at jdk.jpackage/jdk.jpackage.internal.LinuxDebBundler.lambda$initLibProvidersLookup$13(LinuxDebBundler.java:245)
	at jdk.jpackage/jdk.jpackage.internal.LibProvidersLookup.lambda$execute$1(LibProvidersLookup.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at jdk.jpackage/jdk.jpackage.internal.LibProvidersLookup.execute(LibProvidersLookup.java:84)
	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.getListOfNeededPackages(LinuxPackageBundler.java:197)
	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.createDefaultReplacementData(LinuxPackageBundler.java:225)
	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.execute(LinuxPackageBundler.java:153)
	at jdk.jpackage/jdk.jpackage.internal.Arguments.generateBundle(Arguments.java:674)
	at jdk.jpackage/jdk.jpackage.internal.Arguments.processArguments(Arguments.java:551)
	at jdk.jpackage/jdk.jpackage.main.Main.execute(Main.java:91)
	at jdk.jpackage/jdk.jpackage.main.Main.main(Main.java:52)
[13:24:13.530] Running dpkg
[13:24:13.665] Command [PID: 936658]:
    dpkg -S /lib/x86_64-linux-gnu/libmd.so.0
[13:24:13.665] Output:
    dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libmd.so.0
[13:24:13.665] Returned: 1
```

**Comment by sxa** [comment]
Noting that this is a known issue and cannot be easily fixed by us as it's a change in how the packages in Ubuntu 24.04 are put together. (Will get relevant link later)

**Comment by sxa** [comment]
Yep looking at the triage issue it seems to be the same issue in the jpackage tests that we have seen before and it's covered by https://github.com/adoptium/aqa-tests/issues/5383 so I'm going to close this stove that's where the analysis has been done.
