### ISSUE TITLE
build-skytap-solaris10-x64-1 build git issues?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3695]
Node build-skytap-solaris10-x64-1 fails to build jdk8u due to:
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/505/console
```
08:40:23  [CHECKOUT] Checking out Adopt Pipelines https://github.com/adoptium/ci-jenkins-pipelines.git : master
[Pipeline] checkout
08:40:23  The recommended git tool is: /usr/local/bin/git
08:40:23  No credentials specified
08:40:23  Fetching changes from the remote Git repository
08:40:23  ERROR: Error fetching remote repo 'origin'
08:40:23  hudson.plugins.git.GitException: Failed to fetch from https://github.com/adoptium/ci-jenkins-pipelines.git
08:40:23  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
08:40:23  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1241)
08:40:23  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
08:40:23  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:136)
08:40:23  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:101)
08:40:23  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:88)
08:40:23  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
08:40:23  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
08:40:23  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
08:40:23  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
08:40:23  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
08:40:23  	at java.base/java.lang.Thread.run(Thread.java:840)
08:40:23  Caused by: hudson.plugins.git.GitException: Command "/usr/local/bin/git fetch --tags --force --progress -- https://github.com/adoptium/ci-jenkins-pipelines.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
08:40:23  stdout: 
08:40:23  stderr: git: 'remote-https' is not a git command. See 'git --help'.
08:40:23  fatal: full write to remote helper failed: Broken pipe
```

**Comment by steelhead31** [comment]
Git installation appeared to be corrupt, and vagrant machine was also not in good health, I've rebuilt the vagrant box, in a similar fashion to the azure machines, and a new build is running here, which is looking promising.. https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/508/console

**Comment by steelhead31** [comment]
Build has now completed ok, so closing.
