### ISSUE TITLE
test-azure-win2022-x64-1 jenkins service failing to start

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3733]
Im seeing this in the error log
```
INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check
Sep 16, 2024 2:11:13 PM hudson.remoting.Launcher$CuiListener error
java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
```

**Comment by steelhead31** [comment]
Agent has been restarted, its worth noting, that for the test-windows-xxxx boxes, the jenkins agent cannot be run as a service ( so I've disabled the service ). Running the agent as a service causes a number of tests to fail, ( most notably the packaging & wix tests ), as they require the agent process to have a "console" available... this works fine when the agent is launched via the command line ( c:\jenkins\start.bat ). This batch file must be run as the jenkins user.
