### ISSUE TITLE
Two of three agents with label 'https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&sw.os.linux&&!(centos6%7C%7Crhel6)&&sw.tool.docker/' get git issues

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3840]
[test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel7%2Dx64%2D1/) [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Dubuntu1604%2Dx64%2D1/) are hitting the following errors

https://ci.adoptium.net/job/Grinder/11942/console
https://ci.adoptium.net/job/Grinder/11944/console
https://ci.adoptium.net/job/Grinder/11947/console

```
10:24:01  ERROR: Error cloning remote repo 'origin'
10:24:01  hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
10:24:01  stdout: 
10:24:01  stderr: fatal: unable to access 'https://github.com/adoptium/aqa-tests.git/': Failed to connect to github.com port 443: Connection timed out
10:24:01  
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)
10:24:01  	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
10:24:01  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
10:24:01  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:24:01  	at hudson.remoting.Request$2.run(Request.java:377)
10:24:01  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:24:01  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:24:01  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:24:01  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:24:01  	at java.base/java.lang.Thread.run(Thread.java:833)
10:24:01  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-ibmcloud-ubuntu1604-x64-1
10:24:01  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1826)
10:24:01  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
10:24:01  		at hudson.remoting.Channel.call(Channel.java:1042)
10:24:01  		at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)
10:24:01  		at jdk.internal.reflect.GeneratedMethodAccessor487.invoke(Unknown Source)
10:24:01  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:24:01  		at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

**Comment by sxa** [comment]
@AdamBrousseau It looks like outbound connections have been blocked from the ibmcloud linux machines we discussed yesterday in https://github.com/adoptium/infrastructure/issues/3331#issuecomment-2521227600 - can that restriction be lifted?

**Comment by sxa** [comment]
I've marked the three `ibmcloud` machines offline in jenkins for now.

**Comment by sxa** [comment]
Brought them back online and checked again today - machines are still unable to contact github. Marked them offline again:
- https://ci.adoptium.net/job/Grinder/12095/console
- https://ci.adoptium.net/job/Grinder/12098/console

**Comment by sxa** [comment]
Now resolved with IBM. The restriction has been updated and the machines can clone from GitHub again
